/* RE:AMP! — CHAPTER 1 「제로 데시벨」 · 4월 7일 ~ 4월 20일 · 0dB 오픈 마이크
   Branches: which shop you walk into first (1-4) · what you tell Rui about the open mic (1-7) · how the open mic goes (1-9). */
'use strict';
Object.assign(SPEAKER, { '점원': { role: '사이드B', c: '#8FA8FF' }, '가게 안쪽': { role: '', c: '#8FA8FF' }, '사회자': { role: '0dB OPEN MIC', c: '#8FA8FF' } });

/* ---------- first meetings (also played from TOWN for the two shops you didn't walk into) ---------- */
const REN_MEET = S('REN_MEET', '첫 만남 · 멘야 도돈 (렌)', [
  { text: '가게 안은 좁다. 카운터 여덟 자리에 손님은 한 명도 없다.' },
  { text: '카운터 안쪽에서 키 큰 남자가 파를 썰고 있다. 탁, 탁, 탁. 밖에서 들은 그 소리다.' },
  { who: '키 큰 점원', ch: 'ren', ex: 'neutral', text: '어서 오세요. 편한 데 앉으세요.' },
  { text: '머리가 문틀에 닿을 만큼 크고 눈매가 사납다. 그런데 목소리는 조용하다.' },
  { who: '키 큰 점원', ch: 'ren', ex: 'neutral', text: '뭐로 드릴까요?' },
  { choice: ['"제일 잘 나가는 걸로요."', '"칼질 소리가 되게 일정하네요."', '"차슈 추가해 주세요."'], ch: 'ren', ex: 'neutral', eff: [{ bond: { ren: 1 }, money: -900 }, { bond: { ren: 3 }, money: -900 }, { bond: { ren: 1 }, money: -1200 }] },
  { who: '키 큰 점원', ch: 'ren', ex: ['neutral', 'surprise', 'smile'], text: ['간장이요. 5분 걸려요.', '……들리세요?', '두 장 더 얹어 드릴게요. 오늘 첫 손님이라서요.'] },
  { if: IF.p(1), who: '키 큰 점원', ch: 'ren', ex: 'shy', text: '120이에요. 파는 그 속도로 썰어야 고르게 썰리거든요.' },
  { if: IF.p(1), who: '@NAME', text: '120이요?' },
  { if: IF.p(1), who: '키 큰 점원', ch: 'ren', ex: 'neutral', text: 'BPM이요. 아, 신경 쓰지 마세요. 버릇이라.' },
  { text: '면 삶는 물이 끓고, 국자가 냄비 가장자리를 두 번 친다. 소리마다 간격이 맞는다.' },
  { who: '가게 안쪽', text: '렌, 불 줄여라. 국물 넘친다.' },
  { who: '키 큰 점원', ch: 'ren', ex: 'neutral', text: '네.' },
  { text: '렌이라고 불린 남자가 불을 줄이고 그릇을 내 앞에 내려놓는다. 그릇 놓는 소리까지 박자에 맞았다.' },
  { who: '렌', ch: 'ren', ex: 'neutral', text: '……손님, 손끝이 딱딱하시네요.' },
  { who: '@NAME', text: '네?' },
  { who: '렌', ch: 'ren', ex: 'shy', text: '아, 죄송해요. 줄 누르는 손 같아서요.' },
  { choice: ['"예전에 좀 쳤어요."', '"그냥 굳은살이에요."'], ch: 'ren', ex: 'shy', eff: [{ bond: { ren: 1 } }, {}] },
  { who: '렌', ch: 'ren', ex: ['smile', 'neutral'], text: ['그렇구나. 저도 예전에 좀 쳤어요.', '그렇구나.'] },
  { text: '렌은 더 묻지 않고 행주로 카운터를 닦았다. 벽에 드럼 스틱 한 쌍이 걸려 있다. 끝이 하얗게 닳았다.' },
  { who: '렌', ch: 'ren', ex: 'smile', text: '천천히 드세요. 국물 식으면 짜져요.', eff: { hp: 8 } },
]);

const NATSU_MEET = S('NATSU_MEET', '첫 만남 · 헌옷가게 (나츠)', [
  { text: '헌옷가게 가판대 옆에서 앞치마를 두른 금발 남자애가 기타를 안고 있다. 머리에는 얇은 헤어밴드를 했다.' },
  { text: '손님을 부르는 건지 연습을 하는 건지 모르겠다. C, G, Am까지 치고 F로 넘어간다.' },
  { text: 'F에서 또 소리가 죽었다.' },
  { who: '헌옷가게 알바', ch: 'natsu', ex: 'pout', text: '아, 진짜. 왜 너만 안 되냐고.' },
  { who: '헌옷가게 알바', ch: 'natsu', ex: 'surprise', text: '아, 어서 오세요! 오늘 청재킷 30퍼센트……' },
  { who: '헌옷가게 알바', ch: 'natsu', ex: 'surprise', text: '……어?' },
  { text: '그 애가 기타를 안고 그대로 굳었다. 눈이 점점 커진다.' },
  { who: '헌옷가게 알바', ch: 'natsu', ex: 'admire', text: '혹시…… 아니다. 아니죠? 아닌가?' },
  { choice: ['"F는 검지를 좀 더 눕혀 봐."', '"뭐가?"', '"청재킷 보러 왔는데."'], ch: 'natsu', ex: 'admire', eff: [{ bond: { natsu: 3 } }, { bond: { natsu: 1 } }, { bond: { natsu: 1 } }] },
  { if: IF.p(0), who: '헌옷가게 알바', ch: 'natsu', ex: 'surprise', text: '이렇게요?' },
  { if: IF.p(0), text: '검지를 눕히자 여섯 줄이 한 번에 울렸다. 조금 떨리긴 해도 분명히 F다.' },
  { if: IF.p(0), who: '헌옷가게 알바', ch: 'natsu', ex: 'admire', text: '났다. 소리 났어요!' },
  { if: IF.p(1), who: '헌옷가게 알바', ch: 'natsu', ex: 'shy', text: '아, 아니에요. 아는 사람이랑 너무 닮아서요.' },
  { if: IF.p(2), who: '헌옷가게 알바', ch: 'natsu', ex: 'grin', text: '아, 네! 이쪽이요! 이거 진짜 싸게 나온 거예요!' },
  { who: '가게 안쪽', text: '나츠! 가판대 좀 들여놔. 비 온대.' },
  { who: '헌옷가게 알바', ch: 'natsu', ex: 'neutral', text: '네에! 금방요!' },
  { who: '나츠', ch: 'natsu', ex: 'grin', text: '저 주말엔 계속 여기 있어요. 또 오세요!' },
  { text: '나츠라고 불린 애가 가판대를 끌고 들어가다가 문 앞에서 한 번 더 돌아봤다.' },
  { who: '나츠', ch: 'natsu', ex: 'shy', text: '……진짜 아니죠?' },
  { text: '대답하기 전에 문이 닫혔다.' },
]);

const REI_MEET = S('REI_MEET', '첫 만남 · 레코드샵 (레이)', [
  { text: '레코드샵은 좁고, 중고 LP와 오래된 종이 냄새가 난다. 가게 스피커에서 피아노 왈츠가 흘러나온다.' },
  { text: '클래식 악보 코너 앞에 누가 서 있다. 긴 머리를 뒤로 묶고, 악보를 펼친 채 움직이지 않는다.' },
  { text: 'LP를 넘기다 보니 발끝이 음악을 따라 바닥을 두드리고 있었다.' },
  { who: '악보를 든 여자', ch: 'rei', ex: 'annoyed', text: '저기.' },
  { who: '악보를 든 여자', ch: 'rei', ex: 'annoyed', text: '발, 그만. 그리고 틀렸어. 이건 3박자야.' },
  { choice: ['"미안. 버릇이라."', '"방금 곡 바뀌었는데. 이건 4박자야."', '(발을 멈추고 LP만 넘긴다)'], ch: 'rei', ex: 'annoyed', eff: [{ bond: { rei: 1 } }, { bond: { rei: 3 } }, { bond: { rei: 1 } }] },
  { who: '악보를 든 여자', ch: 'rei', ex: ['neutral', 'surprise', 'smirk'], text: ['버릇이면 고쳐. 무대에서 제일 먼저 튀어나오는 게 버릇이니까.', '……그러네. 곡이 바뀌었어.', '멈출 줄은 아네.'] },
  { if: IF.p(1), who: '악보를 든 여자', ch: 'rei', ex: 'shy', text: '이번엔 네 말이 맞아.' },
  { text: '그 사람은 악보를 덮고 계산대로 갔다.' },
  { who: '점원', text: '시라유키 레이 님, 예약하신 악보 들어왔어요. 이번에도 복사본밖에 없네요.' },
  { who: '악보를 든 여자', ch: 'rei', ex: 'neutral', text: '원본은 절판이니까요. 괜찮아요.' },
  { text: '레이라고 불린 사람이 봉투를 받아 들고 문을 나가다가 멈췄다.' },
  { who: '레이', ch: 'rei', ex: 'neutral', text: '너. 굳은살 위치 보니까 현악기 했지.' },
  { who: '레이', ch: 'rei', ex: 'smirk', text: '근데 한동안 안 쳤네. 벗겨지는 중이야.' },
  { choice: ['"그걸 어떻게 알아?"', '"……신경 쓰지 마."'], ch: 'rei', ex: 'smirk', eff: [{ bond: { rei: 1 } }, {}] },
  { who: '레이', ch: 'rei', ex: ['sad', 'neutral'], text: ['안 치는 손은 금방 보여. 나도 한동안 그랬거든.', '신경 안 써. 그냥 남의 손 보는 버릇이 있어서 그래.'] },
  { text: '문에 달린 종이 한 번 울리고, 가게에는 다시 왈츠만 남았다.' },
]);

/* ---------- 1-1 · the half-lit sign ---------- */
const E1_1 = S('E1_1', '1-1 · 반쯤 꺼진 간판', [
  { text: '월요일 저녁, 여섯 시 오 분 전이다.' },
  { text: '상점가 끝에 지하로 내려가는 계단이 있다. 「0dB」 간판은 불이 반쯤 나가 있다.' },
  { text: '지난 1년 동안은 이 앞을 지날 때마다 일부러 길을 건넜다.' },
  { who: '세리자와 점장', text: '오 분 일찍 왔네. 대답은 들은 걸로 할게.' },
  { who: '@NAME', text: '아직 아무 말도 안 했는데요.' },
  { who: '세리자와 점장', text: '여기까지 내려온 게 대답이지. 들어와.' },
  { bg: 'stage', text: '지하 1층 홀은 관객이 80명만 들어와도 꽉 찬다. 천장 조명 몇 개는 꺼진 채 매달려 있다.' },
  { who: '세리자와 점장', text: '일은 간단해. 공연 있는 날 오후에 와서 케이블 깔고, 끝나면 정리하고.' },
  { who: '세리자와 점장', text: '시급은 짜. 대신 연습실은 비어 있으면 공짜로 써.' },
  { text: '무대 쪽에서 마이크 테스트 소리가 들린다. 원, 투. 원, 투.' },
  { text: '마이크 앞에 누가 서 있다. 얼굴 아래쪽을 검은 마스크로 가렸다.' },
  { who: '마스크 쓴 여자', ch: 'rui', ex: 'pout', text: '점장님, 모니터에서 또 하울링 나요. 이거 언제 고쳐 줘요?' },
  { who: '세리자와 점장', text: '마침 고칠 사람 왔어. 루이, 오늘부터 여기서 일할 애야.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '아, 그래요? 잘 부탁……' },
  { who: '루이', ch: 'rui', ex: 'surprise', text: '……잠깐만.' },
  { who: '루이', ch: 'rui', ex: 'surprise', text: '너, 그 영상에 나온 사람 맞지? 무대에서 굳어 있다가 쓰러졌잖아.' },
  { choice: ['"사람 잘못 봤어."', '"……맞아."', '(말없이 모니터 스피커 쪽으로 간다)'], ch: 'rui', ex: 'surprise', eff: [{ bond: { rui: 0 }, mt: -1 }, { bond: { rui: 2 }, mt: -3 }, { bond: { rui: 1 } }] },
  { who: '루이', ch: 'rui', ex: ['pout', 'neutral', 'surprise'], text: ['그래? 목소리까지 똑같은데.', '……그렇게 바로 인정할 줄은 몰랐네.', '대답도 안 하고 일부터 하는 거야?'] },
  { who: '세리자와 점장', text: '루이, 괴롭히지 마. 얘 이제 직원이야.' },
  { who: '루이', ch: 'rui', ex: 'pout', text: '안 괴롭혔거든요. 확인만 했어요.' },
  { text: '모니터 스피커 뒤쪽 케이블을 뽑았다가 다시 꽂는다. 생각보다 손이 먼저 움직였다.' },
  { text: '하울링이 멈추고 홀이 조용해진다.' },
  { text: '조용해지자 귀 안쪽이 다시 울리기 시작한다.', fx: 'tinnitus' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '……고쳤네.' },
  { who: '루이', ch: 'rui', ex: 'shy', text: '고치라고 한 건 점장님이지만…… 고마워.' },
  { text: '루이는 마이크를 스탠드에 꽂아 두고 무대 뒤로 사라졌다.' },
  { who: '세리자와 점장', text: '매주 오픈 마이크 자리 달라고 찾아오는 애야. 노래는 좋은데, 반주해 줄 사람이 잘 안 붙어.' },
  { who: '세리자와 점장', text: '다음 오픈 마이크는 19일 토요일. 너도 나가고 싶으면 말하고.' },
  { who: '@NAME', text: '저는 케이블 감으러 온 건데요.' },
  { who: '세리자와 점장', text: '알아. 그러니까 나가고 싶어지면 말하라고.' },
]);

/* ---------- 1-2 · how to coil a cable ---------- */
const E1_2 = S('E1_2', '1-2 · 케이블 감는 법', [
  { text: '공연 네 시간 전인데 무대 위에는 케이블이 잔뜩 쌓여 있다.' },
  { who: '세리자와 점장', text: '감는 법 기억나? 팔꿈치에 감지 말고 손으로 원 그리면서. 꼬이면 다음 사람이 고생해.' },
  { text: '한 바퀴는 바로 감고, 다음 바퀴는 뒤집어서 감는다. 다행히 감는 법은 아직 안 잊었다.' },
  { who: '세리자와 점장', text: '제일 깔끔하게 감는 건 여전하네.' },
  { who: '세리자와 점장', text: '나도 옛날에 여기서 무대 섰었어. 줄 끊어지고, 앰프 나가고, 관객 반이 나간 날도 있었지.' },
  { who: '세리자와 점장', text: '그래도 다음 주에 또 섰어. 그러다 보니 가게까지 차렸고.' },
  { choice: ['"점장님은 그날 방송 봤어요?"', '"다음 케이블 주세요."'], eff: [{ mt: -1, flags: { askedBroadcast: true } }, { mt: 1 }] },
  { who: '세리자와 점장', text: ['봤지. 근데 좀 이상하더라. 무대 조명은 끝까지 켜져 있었거든.', '좋아. 이 속도면 개장 전에 끝나겠다.'] },
  { if: IF.p(0), who: '세리자와 점장', text: '전기가 나간 게 아니었다는 얘기야. 그 얘기는 나중에 하자. 오늘은 케이블.' },
  { bg: 'backstage', text: '공연이 끝나고 바닥을 닦는다. 스피커를 꺼도 홀에는 사람들 말소리가 한참 남아 있었다.' },
  { who: '세리자와 점장', text: '수고했어. 첫날 일당.' },
  { who: '세리자와 점장', text: '아, 그리고 가게 사진 계정에 오늘 거 올렸어. 네 손만 나왔으니까 걱정 마.' },
]);

/* ---------- 1-3 · a walk through Nagisaka (the first fork) ---------- */
const E1_3 = S('E1_3', '1-3 · 나기사카 산책', [
  { text: '알바가 끝나고 상점가를 걷는다. 이 시간이면 셔터를 내린 가게가 반이다.' },
  { text: '이어폰은 오른쪽에만 꽂았다. 곡이 넘어가는 사이사이에 바깥 소리가 섞여 들어온다.' },
  { text: '고가 옆 라멘집에서 탁, 탁, 탁, 칼이 도마를 치는 소리가 난다. 간격이 이상할 만큼 일정하다.' },
  { text: '헌옷가게 앞에서는 누가 기타를 친다. C, G, Am까지는 좋은데 F에서 소리가 죽는다.' },
  { text: '레코드샵 문틈으로 피아노 곡이 흘러나온다. 하나, 둘, 셋. 왈츠다.' },
  { text: '1년 동안 음악을 안 들은 건 아니다. 그래도 이렇게 소리를 따라 걸어 본 건 오랜만이다.' },
  { choice: ['라멘집 문을 연다', '헌옷가게 앞에서 멈춘다', '레코드샵에 들어간다'], eff: [{ flags: { first: 'ren' } }, { flags: { first: 'natsu' } }, { flags: { first: 'rei' } }] },
]);

/* ---------- 1-5 · a frog DM ---------- */
const E1_5 = S('E1_5', '1-5 · 개구리 DM', [
  { text: '토요일 밤, 침대에 누워 휴대폰만 보고 있다.' },
  { text: '정신을 차려 보니 PULSE 검색창에 「47초」를 치고 있었다.' },
  { text: '#47초프리즈 태그에 오늘도 누가 그 클립을 올렸다. 조회수는 아직도 올라간다.' },
  { text: '댓글은 안 읽기로 했다. 그래도 첫 줄은 눈에 들어온다.', eff: { mt: -3 } },
  { text: 'DM 알림이 하나 왔다. 프로필 사진이 개구리다.', fx: 'buzz' },
  { who: '@kero_P', text: '갑자기 연락드려서 죄송해요.' },
  { who: '@kero_P', text: '0dB 계정에 올라온 사진 봤어요. 케이블 감는 손만 나온 사진이요.' },
  { who: '@kero_P', text: '그 손 알아요. 1년 전에 맨 앞줄에서 봤거든요.' },
  { who: '@kero_P', text: '답장은 안 하셔도 돼요. 아직 거기 계신 것 같아서 반가웠어요.' },
  { choice: ['"누구세요?"', '"맨 앞줄이었으면 그날 다 봤겠네요."', '(읽기만 한다)'], eff: [{ bond: { koto: 2 }, flags: { kotoReply: true } }, { bond: { koto: 3 }, mt: -2, flags: { kotoReply: true } }, { bond: { koto: 0 } }] },
  { who: '@kero_P', text: ['kero_P예요. 곡 만들어요. 개구리는 그냥 좋아해서요.', '네. 다 봤어요.', '(개구리 이모티콘)'] },
  { if: IF.p(0), who: '@kero_P', text: '시간 나시면 들어 주세요. 안 들으셔도 되고요.' },
  { if: IF.p(0), text: '링크가 하나 왔다. 보컬 없는 곡이다. 베이스 라인이 이상할 만큼 귀에 남는다.' },
  { if: IF.p(1), who: '@kero_P', text: '사람들이 모르는 것까지요.' },
  { if: IF.p(1), text: '무슨 뜻이냐고 보냈지만, 그 뒤로는 읽음 표시만 떴다.' },
  { if: IF.p(2), text: '답장을 쓰다가 지웠다. 읽음 표시는 이미 떴을 거다.' },
  { text: '휴대폰 화면을 끈다. 오픈 마이크는 다음 주 토요일이다.' },
]);

/* ---------- 1-6 · the empty seat ---------- */
const E1_6 = S('E1_6', '1-6 · 비어 있는 자리', [
  { text: '월요일은 공연이 없어서 0dB도 조용하다. 청소기를 돌리고 나니 할 일이 없다.' },
  { text: '무대에서 누가 마스크를 쓰고 반주도 없이 혼자 노래하고 있다.' },
  { text: '목소리가 홀 끝까지 또렷하게 들린다. 마스크를 썼는데도 전혀 먹먹하지 않다.' },
  { text: '후렴 직전에 노래가 뚝 끊겼다.' },
  { who: '루이', ch: 'rui', ex: 'pout', text: '거기 서서 들을 거면 박수라도 치든가.' },
  { choice: ['(박수를 친다)', '"거기서 왜 멈췄어?"', '"미안. 청소 중이었어."'], ch: 'rui', ex: 'pout', eff: [{ bond: { rui: 2 } }, { bond: { rui: 1 } }, {}] },
  { who: '루이', ch: 'rui', ex: ['shy', 'neutral', 'pout'], text: ['……됐어, 그만 쳐. 진짜 치라는 거 아니었어.', '다음 마디부터 반주가 들어와야 하거든. 없으니까 멈춘 거야.', '청소는 무슨. 걸레 들고 서 있기만 했잖아.'] },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '토요일 오픈 마이크, 나 나가.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '반주해 주기로 한 사람이 어제 못 하겠대. 이유는 안 물어봤어.' },
  { who: '루이', ch: 'rui', ex: 'sad', text: '……너 기타 치잖아. 베이스도 치고, 드럼도 치고. 영상 다 봤어.' },
  { who: '@NAME', text: '그 영상 말고 다른 것도 봤구나.' },
  { who: '루이', ch: 'rui', ex: 'pout', text: '봤으면 뭐. 반주해 달라는 거 아니야. 자리가 비어 있다는 거지.' },
  { choice: ['"내가 칠게."', '"난 무대에 안 서."', '"……생각해 볼게."'], ch: 'rui', ex: 'neutral', eff: [{ bond: { rui: 3 }, mt: -2, flags: { om: 'yes' } }, { bond: { rui: -1 }, flags: { om: 'no' } }, { bond: { rui: 1 }, flags: { om: 'maybe' } }] },
  { who: '루이', ch: 'rui', ex: ['surprise', 'sad', 'pout'], text: ['……진짜? 방금 한 말 취소 안 돼.', '알았어. 그럼 됐어.', '생각은 토요일 전까지만 해.'] },
  { if: IF.p(0), who: '루이', ch: 'rui', ex: 'shy', text: '수요일 밤에 신사 계단으로 와. 거기서 맞춰 보자. 여기는 점장님이 시끄럽대.' },
  { if: IF.p(1), text: '루이는 마이크 케이블을 둘둘 말아 넣고 나가 버렸다. 케이블이 엉망으로 감겨 있다.' },
  { if: IF.p(1), text: '다시 풀어서 한 바퀴는 바로, 한 바퀴는 뒤집어서 감는다.' },
  { if: IF.p(2), who: '루이', ch: 'rui', ex: 'neutral', text: '악보 두고 갈게. 보기만 해. 치라는 거 아니야.' },
]);

/* ---------- 1-7 · three ways to the open mic ---------- */
const E1_7A = S('E1_7A', '1-7A · 신사 계단의 리허설', [
  { text: '수요일 밤, 신사로 올라가는 돌계단은 백 개가 넘는다. 루이는 중간쯤에 앉아 있었다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '늦었어. 3분.' },
  { who: '@NAME', text: '계단이 이렇게 많은 줄 몰랐어.' },
  { who: '루이', ch: 'rui', ex: 'smile', text: '그래서 여기 오는 거야. 올라오다 지쳐서 아무도 안 와.' },
  { text: '기타 케이스를 연다. 앰프가 없어서 생음으로 친다. 돌계단에 부딪힌 소리가 생각보다 크게 울린다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '곡은 이걸로 하자.' },
  { text: '루이가 휴대폰 화면을 내민다. 곡 제목을 보고 손이 멈췄다.' },
  { text: '「カウント四つ」, 내가 쓴 SIGNAL LOST의 첫 곡이다.' },
  { choice: ['"……왜 하필 이 곡이야."', '"다른 곡은 없어?"', '(말없이 첫 코드를 잡는다)'], ch: 'rui', ex: 'neutral', eff: [{ bond: { rui: 1 } }, { mt: -2 }, { bond: { rui: 2 }, mt: -3 }] },
  { who: '루이', ch: 'rui', ex: ['sad', 'pout', 'surprise'], text: ['너랑 내가 둘 다 아는 곡이 이것밖에 없어서.', '있지. 근데 네가 제일 잘 치는 건 이거잖아.', '……바로 치네.'] },
  { text: '첫 소절에 루이의 목소리가 들어온다. 마스크 너머인데도 가사가 또렷하다.' },
  { text: '후렴 앞에 쉼표가 있어서 한 박 동안 아무 소리도 나지 않는다.' },
  { text: '그 한 박이 길다. 손가락이 줄 위에서 굳는다.', fx: 'tinnitus', eff: { mt: -2 } },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '……하나, 둘.' },
  { text: '루이가 작게 박자를 세 줬다. 셋에서 손이 다시 움직였다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '쉼표 나올 때마다 멈추네.' },
  { choice: ['"버릇이야."', '"조용한 게 좀 무서워서."'], ch: 'rui', ex: 'neutral', eff: [{}, { bond: { rui: 2 }, mt: 3, flags: { toldRuiFear: true } }] },
  { who: '루이', ch: 'rui', ex: ['pout', 'sad'], text: ['그럼 고쳐. 토요일까지.', '……그래.'] },
  { if: IF.p(1), who: '루이', ch: 'rui', ex: 'sad', text: '나도 무서운 거 있어. 그래서 이거 쓰고 부르는 거고.' },
  { if: IF.p(1), text: '루이는 마스크 끈을 손가락으로 한 번 튕겼다. 더 말하지는 않았다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '쉼표 나올 때마다 내가 세 줄게. 하나, 둘. 그럼 셋에 들어와.' },
  { text: '계단 아래로 전철이 지나간다. 루이는 그 소리가 다 지나갈 때까지 기다렸다가 다시 첫 소절을 불렀다.' },
]);
const E1_7B = S('E1_7B', '1-7B · 1년 만의 케이스', [
  { text: '철길 고가 밑에 있는 렌탈 스튜디오에 왔다. 0dB 직원이라고 하니 점장이 한 시간을 공짜로 잡아 줬다.' },
  { text: '루이가 두고 간 악보를 보면대에 올린다. 맨 위에 적힌 제목을 보고 한참 서 있었다.' },
  { text: '「カウント四つ」, 내가 쓴 SIGNAL LOST의 첫 곡이다.' },
  { text: '1년 만에 케이스를 연다. 줄은 녹이 슬었고, 손끝 굳은살도 반쯤 없어졌다.' },
  { text: '머리 위로 전철이 지나간다. 그 소리에 묻히듯 첫 음을 쳐 본다.' },
]);
const E1_7B2 = S('E1_7B2', '1-7B · 연습 끝', [
  { text: '중간에 몇 번 손이 멈췄지만 한 곡을 끝까지 쳤다.' },
  { if: IF.last(3), text: '끝까지 치고 나니 손이 떨린다. 그래도 기분이 나쁘진 않다.' },
  { if: IF.not(IF.last(3)), text: '쉼표마다 손이 늦었다. 루이라면 바로 알아챘을 거다.' },
  { text: '마지막 음이 끝나고 스튜디오가 조용해지자 또 귀가 울린다.', fx: 'tinnitus' },
  { text: '휴대폰을 꺼낸다. 루이와의 대화창에는 아직 아무것도 없다.' },
  { choice: ['"토요일에 칠게."라고 보낸다', '(보내지 않는다)'], eff: [{ bond: { rui: 2 }, flags: { om2: 'yes' } }, { flags: { om2: 'no' } }] },
  { if: IF.p(0), text: '1분도 안 돼서 "늦어."라고 답장이 왔다. 조금 뒤에 "금요일에 한 번 맞춰 봐."라고 하나 더 왔다.' },
  { if: IF.p(1), text: '휴대폰을 주머니에 넣었다. 악보는 버리지 않고 접어서 가방에 넣었다.' },
]);
const E1_7C = S('E1_7C', '1-7C · 믹서 앞자리', [
  { text: '목요일, 개장 전 0dB에서 점장이 믹서 앞자리를 턱으로 가리킨다.' },
  { who: '세리자와 점장', text: '토요일 오픈 마이크, 음향 네가 봐.' },
  { who: '@NAME', text: '루이한테 들었어요?' },
  { who: '세리자와 점장', text: '걔가 말을 해? 케이블 감긴 꼴 보고 알았지.' },
  { who: '세리자와 점장', text: '무대에 안 서겠다는 건 네 맘이야. 대신 무대 옆에는 있어. 여기 직원이잖아.' },
  { choice: ['"음향이라면 할게요."', '"그날 쉬면 안 돼요?"'], eff: [{ mt: 1 }, { mt: -2 }] },
  { who: '세리자와 점장', text: ['그래. 페이더 올리는 손은 무대 위랑 똑같이 떨려. 해 보면 알아.', '안 돼. 사람 없어.'] },
  { text: '점장이 벽에 붙은 사진 한 장을 가리킨다. 머리를 짧게 민 여자가 부서진 기타를 들고 웃고 있다.' },
  { who: '세리자와 점장', text: '나. 스물두 살. 첫 곡 첫 소절에서 줄 끊어진 날.' },
  { who: '세리자와 점장', text: '그날 이후로 무대 서는 게 무서웠냐고? 무서웠지. 그래서 무서운 대로 다음 주에 또 섰어.' },
  { text: '점장은 그 말만 하고 사무실로 들어갔다. 믹서의 페이더 하나가 반쯤 올라가 있었다.' },
]);

/* ---------- 1-8 · the open mic ---------- */
const E1_8 = S('E1_8', '1-8 · 오픈 마이크', [
  { text: '토요일 밤 여덟 시, 0dB 오픈 마이크가 시작된다.' },
  { text: '객석에는 스무 명쯤 있다. 대부분 자기 순서를 기다리는 출연자와 그 친구들이다.' },
  { if: g => g.flags.om === 'yes' || g.flags.om2 === 'yes', bg: 'backstage', text: '대기실에서 루이는 아까부터 마스크 끈을 고쳐 매고 있다.' },
  { if: g => g.flags.om === 'yes' || g.flags.om2 === 'yes', who: '루이', ch: 'rui', ex: 'neutral', text: '떨려?' },
  { if: g => g.flags.om === 'yes' || g.flags.om2 === 'yes', choice: ['"응."', '"아니."', '"너는?"'], ch: 'rui', ex: 'neutral', eff: [{ bond: { rui: 1 } }, {}, { bond: { rui: 2 } }] },
  { if: g => g.flags.om === 'yes' || g.flags.om2 === 'yes', who: '루이', ch: 'rui', ex: ['smile', 'pout', 'shy'], text: ['다행이다. 나만 떨리는 줄 알았어.', '거짓말. 손 차갑잖아.', '……나는 늘 떨려. 그래서 이거 쓰는 거야.'] },
  { if: g => g.flags.om === 'yes' || g.flags.om2 === 'yes', who: '루이', ch: 'rui', ex: 'neutral', text: '쉼표에서 세 줄게. 하나, 둘. 잊지 마.' },
  { if: g => g.flags.om !== 'yes' && g.flags.om2 !== 'yes', text: '믹서 앞에 앉아 있다. 오늘은 음향만 보기로 했다.' },
  { if: g => g.flags.om !== 'yes' && g.flags.om2 !== 'yes', text: '루이 차례다. 루이는 반주 없이 무대에 섰다. 첫 소절이 홀 안에 울려 퍼진다.' },
  { if: g => g.flags.om !== 'yes' && g.flags.om2 !== 'yes', text: '후렴 앞에서 루이의 목소리가 흔들렸다. 반주가 들어와야 할 자리가 비어 있다.' },
  { if: g => g.flags.om !== 'yes' && g.flags.om2 !== 'yes', text: '루이가 믹서 쪽을 봤다. 마스크 위로 눈만 보인다.' },
  { if: g => g.flags.om !== 'yes' && g.flags.om2 !== 'yes', choice: ['(무대 옆 기타를 들고 올라간다)', '(페이더를 올려 목소리를 받쳐 준다)'], eff: [{ bond: { rui: 3 }, mt: -3 }, { bond: { rui: 1 } }] },
  { if: IF.all(g => g.flags.om !== 'yes' && g.flags.om2 !== 'yes', IF.p(1)), who: '세리자와 점장', text: '그걸로 되겠냐. 올라가.' },
  { if: IF.all(g => g.flags.om !== 'yes' && g.flags.om2 !== 'yes', IF.p(1)), text: '점장이 등을 떠밀었다. 정신을 차려 보니 무대 옆에 세워 둔 기타를 들고 있었다.' },
  { if: g => g.flags.om !== 'yes' && g.flags.om2 !== 'yes', text: '무대로 올라가는 계단은 세 칸뿐이었다. 그 세 칸을 1년 동안 한 번도 못 올랐다.' },
  { who: '사회자', text: '다음 순서입니다. 아마네 루이, 그리고……' },
  { text: '조명이 켜진다. 눈앞이 하얘졌다가, 천천히 객석이 보인다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '카운트 넷.' },
]);
const E1_8B = S('E1_8B', '1-8 · 오픈 마이크 · 끝', [
  { text: '마지막 코드가 끝났다.' },
  { text: '울림이 다 사라질 때까지 아무도 움직이지 않았다.' },
]);
const E1_9S = S('E1_9S', '1-9S · 박수 세 번', [
  { text: '박수가 터졌다. 오픈 마이크치고는 꽤 크다.' },
  { who: '관객', text: '와, 뭐야. 잘한다.' },
  { who: '관객', text: '근데 저 기타, 47초 그 사람 아냐?' },
  { who: '관객', text: '그게 뭐 어때서. 방금 거 들었잖아.' },
  { text: '무대에서 내려오자 다리가 풀렸다. 계단 세 칸을 어떻게 내려왔는지 기억이 안 난다.' },
  { who: '루이', ch: 'rui', ex: 'surprise', text: '……쉼표에서 안 멈췄어.' },
  { who: '@NAME', text: '네가 세 줬잖아.' },
  { who: '루이', ch: 'rui', ex: 'smile', text: '안 셌어. 세려고 했는데 네가 먼저 들어왔어.' },
  { text: '루이가 웃었다. 마스크 때문에 눈만 보이는데도 웃는 게 보였다.' },
  { who: '세리자와 점장', text: '다음 달 오픈 마이크도 너희 자리 비워 둘게. 싫으면 말하고.' },
  { who: '루이', ch: 'rui', ex: 'pout', text: '싫다고 안 할 거예요. 얘도요.' },
]);
const E1_9B = S('E1_9B', '1-9B · 쉼표', [
  { text: '박수는 나왔다. 오픈 마이크에서 늘 나오는 정도였다.' },
  { text: '두 번째 후렴 앞 쉼표에서 손이 멈췄다. 한 마디 동안 기타 소리가 없었다.' },
  { text: '그 한 마디를 루이가 반주 없이 혼자 불렀다. 원래 그렇게 부르는 곡처럼 자연스러웠다.' },
  { bg: 'street_night', text: '공연이 끝나고 가게 뒷문 계단에 앉아 있다. 손이 아직 차갑다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '여기 있었네.' },
  { text: '루이가 탄산수 한 캔을 옆에 내려놓는다. 레몬맛이다.' },
  { who: '루이', ch: 'rui', ex: 'pout', text: '멈췄지.' },
  { choice: ['"미안."', '"네가 받아 줘서 살았어."', '(캔을 딴다)'], ch: 'rui', ex: 'pout', eff: [{ bond: { rui: 1 } }, { bond: { rui: 3 } }, { bond: { rui: 1 }, hp: 3 }] },
  { who: '루이', ch: 'rui', ex: ['sad', 'shy', 'neutral'], text: ['사과하지 마. 사과하면 다음에도 멈춰.', '……받아 준 거 아니야. 그냥 계속 부른 거지.', '그거 내 거였는데. 됐어, 마셔.'] },
  { who: '루이', ch: 'rui', ex: 'sad', text: '관객들은 몰랐어. 원래 그런 편곡인 줄 알더라.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '그러니까 다음엔 안 멈추면 돼.' },
  { text: '그 말투가 너무 당연해서 오히려 웃음이 났다.', eff: { mt: 4 } },
]);
const E1_10 = S('E1_10', '1-10 · 다시 열린 케이스', [
  { text: '일요일 오후, 0dB 대기실 벽에는 여러 밴드의 사인이 겹겹이 적혀 있다.' },
  { text: '그중 하나가 SIGNAL LOST다. 네 명의 이름이 삐뚤빼뚤하다. 하루의 이름이 제일 크다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '이거 보고 있었어?' },
  { text: '루이가 마스크를 고쳐 쓰며 옆에 선다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '어제 점장님이 그러더라. 다음 달에 새 밴드 자리 하나 비워 둘 거래.' },
  { who: '루이', ch: 'rui', ex: 'pout', text: '누구 얘긴지는 말 안 했어.' },
  { who: '루이', ch: 'rui', ex: 'shy', text: '……밴드 할 거면 나도 끼워 줘.' },
  { choice: ['"밴드 할 생각 없었는데."', '"보컬 자리는 네 거야."', '"마스크는 계속 쓸 거야?"'], ch: 'rui', ex: 'shy', eff: [{ bond: { rui: 1 } }, { bond: { rui: 3 } }, { bond: { rui: 1 } }] },
  { who: '루이', ch: 'rui', ex: ['pout', 'surprise', 'sad'], text: ['그럼 지금부터 해.', '……당연하지. 다른 사람 주면 가만 안 둬.', '응. 이거 없으면 못 불러. 이유는 아직 말 안 해.'] },
  { if: IF.p(2), who: '@NAME', text: '그럼 아직은 안 물어볼게.' },
  { if: IF.p(2), who: '루이', ch: 'rui', ex: 'shy', text: '……그래 줘.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '근데 둘로는 밴드가 안 되잖아.' },
  { who: '루이', ch: 'rui', ex: 'smile', text: '나머지는 네가 찾아. 넌 이 동네 가게를 벌써 반은 돌았잖아.' },
  { text: '케이스를 닫지 않고 대기실을 나왔다. 1년 동안 한 번도 그런 적이 없었다.' },
]);

CH[1] = {
  no: '01', en: 'CHAPTER 1', name: '제로 데시벨', bg: 'backstage', span: '4월 · 오픈 마이크까지 2주',
  desc: '1년 후. 점장의 전화로 0dB에서 알바를 시작한다. 마스크를 쓴 보컬이 반주할 사람을 찾고 있다.',
  goals: g => [['0dB에서 일하기', !!g.ep['1-2']], ['동네 사람 만나기', !!g.ep['1-5']], ['오픈 마이크 무대', !!g.ep['1-8']], ['첫 멤버', g.joined.includes('rui')]],
  show: '1-8', showName: 'OPEN MIC', end: '1-10',
  forks: [{ c: 3, t: '선택 · 먼저 들어간 가게' }, { c: 6, t: '선택 · 루이에게 한 대답' }, { c: 8, t: '결과 · 오픈 마이크 랭크' }],
  nodes: [
    { id: '1-1', c: 0, l: 2, type: 'talk', t: '반쯤 꺼진 간판', day: 0, time: '저녁', who: 'rui', desc: '0dB 첫 출근. 무대에서 마스크를 쓴 누군가가 마이크 테스트를 하고 있다.', chg: ['루이를 알게 된다'], rw: [],
      steps: [{ adv: E1_1, bg: 'street_night', place: '<b>0dB</b> 앞 · 월요일 저녁' }] },
    { id: '1-2', c: 1, l: 2, type: 'talk', t: '케이블 감는 법', day: 2, time: '오후', desc: '공연 네 시간 전. 점장이 케이블 감는 법을 기억하냐고 묻는다.', chg: ['TOWN과 LIVE가 열린다'], rw: ['¥4,000', '체력 -12'], from: ['1-1'],
      steps: [{ adv: E1_2, bg: 'stage', place: '<b>0dB</b> 홀 · 개장 전' }], eff: { money: 4000, hp: -12 } },
    { id: '1-3', c: 2, l: 2, type: 'talk', t: '나기사카 산책', day: 3, time: '밤', desc: '알바가 끝난 밤, 상점가에서 세 가지 소리가 들린다.', chg: ['어느 가게에 먼저 들어가는지에 따라 먼저 만나는 사람이 달라진다'], rw: [], from: ['1-2'],
      steps: [{ adv: E1_3, bg: 'street_night', place: '<b>나기사카</b> 상점가 · 밤' }], log: g => `들어간 가게 · ${{ ren: '라멘집', natsu: '헌옷가게', rei: '레코드샵' }[g.flags.first]}` },
    { id: '1-4A', c: 3, l: 1, type: 'ev', who: 'ren', t: '칼질 소리', day: 3, time: '밤', alt: true, desc: '고가 옆 라멘집. 카운터 안에서 키 큰 점원이 일정한 박자로 파를 썬다.', chg: ['렌을 알게 된다'], rw: ['체력 +8'], from: ['1-3'], when: IF.f('first', 'ren'),
      steps: [{ adv: REN_MEET, bg: 'ramen_night', place: '<b>멘야 도돈</b> · 밤' }], log: '렌을 만났다' },
    { id: '1-4B', c: 3, l: 2, type: 'ev', who: 'natsu', t: 'F 코드', day: 3, time: '밤', alt: true, desc: '헌옷가게 앞. 앞치마 두른 남자애가 F 코드에서 번번이 막힌다.', chg: ['나츠를 알게 된다'], rw: [], from: ['1-3'], when: IF.f('first', 'natsu'),
      steps: [{ adv: NATSU_MEET, bg: 'thrift_night', place: '<b>상점가 헌옷가게</b> · 밤' }], log: '나츠를 만났다' },
    { id: '1-4C', c: 3, l: 3, type: 'ev', who: 'rei', t: '3박자', day: 3, time: '밤', alt: true, desc: '레코드샵. 악보를 펼친 사람이 발로 박자를 세지 말라고 한다.', chg: ['레이를 알게 된다'], rw: [], from: ['1-3'], when: IF.f('first', 'rei'),
      steps: [{ adv: REI_MEET, bg: 'record_night', place: '<b>레코드샵 사이드B</b> · 밤' }], log: '레이를 만났다' },
    { id: '1-5', c: 4, l: 2, type: 'talk', who: 'koto', t: '개구리 DM', day: 5, time: '밤', desc: '주말 밤, 개구리 프로필에게서 DM이 온다.', chg: ['답장하면 kero_P와 이야기가 이어진다'], rw: [], from: ['1-4A', '1-4B', '1-4C'], hint: '만나지 못한 두 사람은 TOWN에서 만날 수 있어요',
      steps: [{ adv: E1_5, bg: 'river_night', place: '<b>집</b> · 토요일 밤' }], log: g => g.flags.kotoReply ? 'kero_P에게 답장했다' : 'kero_P의 DM을 읽기만 했다' },
    { id: '1-6', c: 5, l: 2, type: 'talk', who: 'rui', t: '비어 있는 자리', day: 7, time: '저녁', desc: '공연 없는 월요일. 루이가 반주 없이 노래하다 후렴 앞에서 멈춘다.', chg: ['오픈 마이크에 어떻게 설지 정해진다'], rw: [], from: ['1-5'],
      steps: [{ adv: E1_6, bg: 'stage', place: '<b>0dB</b> 홀 · 월요일' }], log: g => ({ yes: '루이에게 "내가 칠게"', no: '루이에게 "무대에 안 서"', maybe: '루이에게 "생각해 볼게"' })[g.flags.om] },
    { id: '1-7A', c: 6, l: 1, type: 'ev', who: 'rui', t: '신사 계단의 리허설', day: 9, time: '밤', alt: true, desc: '백 개가 넘는 돌계단 중간에서 루이와 처음 맞춰 본다.', chg: ['쉼표가 무섭다는 걸 루이에게 말할 수 있다'], rw: ['루이 ♥'], from: ['1-6'], when: IF.f('om', 'yes'),
      steps: [{ adv: E1_7A, bg: 'shrine_night', place: '<b>나기사카 신사</b> 돌계단 · 밤' }] },
    { id: '1-7B', c: 6, l: 2, type: 'live', t: '1년 만의 케이스', day: 9, time: '밤', alt: true, desc: '루이가 두고 간 악보를 들고 스튜디오에 간다. 1년 만에 케이스를 연다.', chg: ['연습이 끝나고 루이에게 답장할지 정한다'], rw: ['팬', 'SYNC 없음 (혼자 연습)'], from: ['1-6'], when: IF.f('om', 'maybe'),
      steps: [{ adv: E1_7B, bg: 'studio_night', place: '<b>UNDERPASS 스튜디오</b> · 밤' }, { live: { song: 'count4', len: 'hl', bg: 'studio_night', noFail: true, label: 'SOLO PRACTICE' } }, { adv: E1_7B2, bg: 'studio_night', place: '<b>UNDERPASS 스튜디오</b> · 밤' }],
      log: g => g.flags.om2 === 'yes' ? '연습 후 루이에게 "칠게"' : '연습 후 답장하지 않았다' },
    { id: '1-7C', c: 6, l: 3, type: 'talk', t: '믹서 앞자리', day: 10, time: '오후', alt: true, desc: '무대에 안 서겠다고 하자 점장이 음향을 맡긴다.', chg: ['오픈 마이크 날 믹서 앞에 앉는다'], rw: [], from: ['1-6'], when: IF.f('om', 'no'),
      steps: [{ adv: E1_7C, bg: 'stage', place: '<b>0dB</b> 홀 · 개장 전' }] },
    { id: '1-8', c: 7, l: 2, type: 'live', who: 'rui', t: '오픈 마이크', day: 12, time: '밤', desc: '0dB 오픈 마이크. 루이의 목소리와 1년 만의 무대.', chg: ['랭크 A 이상 → 「박수 세 번」', '랭크 B 이하 → 「쉼표」'], rw: ['팬', '¥', '실패 없음'], from: ['1-7A', '1-7B', '1-7C'], need: { lives: 1 },
      steps: [{ adv: E1_8, bg: 'stage', place: '<b>0dB</b> 오픈 마이크 · 토요일 밤' }, { live: { song: 'count4', len: 'hl', bg: 'stage', noFail: true, ask: '오픈 마이크에서 칠 악기', label: () => `RUI & ${G.name}` } }, { adv: E1_8B, bg: 'stage', place: '<b>0dB</b> 오픈 마이크' }],
      log: g => `오픈 마이크 · ${g.ep['1-8'] && g.ep['1-8'].rank}랭크` },
    { id: '1-9S', c: 8, l: 1, type: 'cut', who: 'rui', t: '박수 세 번', day: 12, time: '밤', alt: true, desc: '박수가 크게 터진다. 쉼표에서 멈추지 않았다.', chg: ['다음 달 오픈 마이크 자리를 받는다'], rw: ['팬 +60', '멘탈 +6'], from: ['1-8'], when: IF.rk('1-8', 3),
      steps: [{ adv: E1_9S, bg: 'backstage', place: '<b>0dB</b> 대기실 · 밤' }], eff: { fans: 60, mt: 6, flags: { omGood: true } } },
    { id: '1-9B', c: 8, l: 3, type: 'talk', who: 'rui', t: '쉼표', day: 12, time: '밤', alt: true, desc: '두 번째 후렴 앞에서 손이 멈췄다. 루이가 그 한 마디를 혼자 불렀다.', chg: ['루이와 둘이서 이야기한다'], rw: ['루이 ♥', '팬 +20'], from: ['1-8'], when: IF.not(IF.rk('1-8', 3)),
      steps: [{ adv: E1_9B, bg: 'backstage', place: '<b>0dB</b> 뒷문 계단 · 밤' }], eff: { fans: 20 } },
    { id: '1-10', c: 9, l: 2, type: 'cut', who: 'rui', t: '다시 열린 케이스', day: 13, time: '오후', desc: '대기실 벽의 SIGNAL LOST 사인. 루이가 먼저 말을 꺼낸다.', chg: ['루이가 밴드에 합류한다', 'CHAPTER 2가 열린다'], rw: ['루이 합류'], from: ['1-9S', '1-9B'],
      steps: [{ adv: E1_10, bg: 'backstage', place: '<b>0dB</b> 대기실 · 일요일' }], eff: { join: 'rui', bond: { rui: 2 } }, log: '루이가 밴드에 들어왔다' },
  ],
};
