/* RE:AMP! — CHAPTER 3 「불협화음」 · 5월 19일 ~ 7월 초 · 0dB 정기 공연 (세 곡, 관객 서른 명)
   Branches: each of Ren / Koto / Rei gets the scene that fits where they stand (not in the band yet → the join scene,
   already in → their trouble) · who the band follows (3-3 → five routes) · the business card (3-5) · the show (3-7). */
'use strict';
const in3 = id => g => !!(g.flags.in3 && g.flags.in3[id]);

const E3_1 = S('E3_1', '3-1 · 공연 다음 날', [
  { text: '월요일 아침, 휴대폰 알림이 평소보다 많다.', fx: 'buzz' },
  { text: '금요일 공연 영상이 PULSE에 올라와 있다. 객석 맨 뒤에서 찍은 1분짜리 영상이다.' },
  { who: 'PULSE', text: '@nagisaka_night · 0dB 평일 밤에 이런 밴드가 있었네. 보컬 누구임?' },
  { who: 'PULSE', text: '@riff_daily · 기타 47초 그 사람 맞지? 이번엔 안 멈췄네ㅋㅋ' },
  { who: 'PULSE', text: '@minori_07 · 멈추는지 보려고 끝까지 봤는데 안 멈춤. 오히려 좋았음' },
  { choice: ['(댓글을 끝까지 읽는다)', '(앱을 끈다)'], eff: [{ mt: -3, fans: 30 }, { mt: 1 }] },
  { if: IF.p(0), text: '나쁜 말이 반, 좋은 말이 반이다. 좋은 말이 반이나 된다는 게 이상했다.' },
  { if: IF.p(1), text: '휴대폰을 뒤집어 놓았다. 진동이 한 번 더 울렸지만 확인하지 않았다.' },
  { bg: 'stage', text: '저녁에는 0dB에 나갔다.' },
  { who: '세리자와 점장', text: '영상 봤어. 조회수가 우리 가게 계정 1년 치보다 많더라.' },
  { who: '세리자와 점장', text: '6월 28일 토요일. 정기 공연 자리 줄게. 한 달에 한 번, 주말 저녁. 세 곡.' },
  { who: '세리자와 점장', text: '이번엔 서른 명은 채워야 돼. 표는 너희가 팔고.' },
  { who: '루이', ch: 'rui', ex: 'surprise', text: '서른 명이요? 지난번엔 다섯 명이었는데요.' },
  { who: '세리자와 점장', text: '그러니까 여섯 배만 늘리면 되잖아.' },
  { if: IF.f('natsuIn', 'later'), text: '그때 누가 계단을 쿵쾅거리며 뛰어 내려왔다.' },
  { if: IF.f('natsuIn', 'later'), who: '나츠', ch: 'natsu', ex: 'admire', text: '선배! B♭! 잡았어요!' },
  { if: IF.f('natsuIn', 'later'), text: '나츠가 숨을 몰아쉬며 기타를 꺼낸다. B♭이 울렸다. 깨끗하지는 않아도 분명한 소리다.' },
  { if: IF.f('natsuIn', 'later'), who: '나츠', ch: 'natsu', ex: 'grin', text: '이제 끼워 주시는 거죠?', eff: { join: 'natsu', bond: { natsu: 3 } } },
  { if: IF.f('natsuIn', 'later'), who: '루이', ch: 'rui', ex: 'pout', text: '시끄러워. 들어와.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '세 곡이면 빈자리부터 채워야 해.' },
  { text: '드럼, 베이스, 건반 중에는 아직 비어 있는 자리도 있고, 채웠지만 아직 어색한 자리도 있다.' },
]);

/* ---------- Ren: not in the band → the fish market · in the band → the shop's debt ---------- */
const E3_2Ra = S('E3_2Ra', '3-2 · 렌 · 새벽 시장', [
  { text: '새벽 다섯 시, 어시장 입구에서 렌이 스티로폼 상자를 두 개씩 들고 걷고 있다.' },
  { who: '렌', ch: 'ren', ex: 'surprise', text: '……여기까지 오셨어요?' },
  { who: '@NAME', text: '점장님이 여기 가면 있을 거라고 해서요.' },
  { who: '렌', ch: 'ren', ex: 'shy', text: '점장님은 다 아시네요.' },
  { text: '렌 옆에서 나이 든 남자가 생선 상자를 들다 허리를 짚는다. 얼굴이 렌과 닮았다.' },
  { who: '렌 아버지', text: '렌, 그건 내가 들게. 너는 손 아껴.' },
  { who: '렌', ch: 'ren', ex: 'neutral', text: '괜찮아요. 아버지 허리를 더 아끼셔야죠.' },
  { who: '렌 아버지', text: '친구냐? 새벽부터 고생이 많네.' },
  { choice: ['(상자를 하나 받아 든다)', '"밴드 얘기 하러 왔어요."'], ch: 'ren', ex: 'neutral', eff: [{ bond: { ren: 2 }, hp: -5 }, { bond: { ren: 1 } }] },
  { if: IF.p(0), text: '상자는 생각보다 무거웠다. 렌은 이걸 두 개씩 들고 있었다.' },
  { if: IF.p(1), who: '렌 아버지', text: '밴드?' },
  { if: IF.p(1), text: '렌의 아버지가 렌을 쳐다봤다. 렌은 대답하지 않고 상자를 수레에 실었다.' },
  { text: '장을 다 보고 가게로 돌아가는 길에 렌이 먼저 입을 열었다.' },
  { who: '렌', ch: 'ren', ex: 'sad', text: '아버지가 작년에 쓰러지셨어요. 그때 가게에 빚이 생겼고요.' },
  { who: '렌', ch: 'ren', ex: 'neutral', text: '밤에 드럼 치는 시간이면 가게를 한 번 더 돌릴 수 있어요. 그래서 봄까지만 한다고 한 거예요.' },
  { who: '렌 아버지', text: '……렌.' },
  { text: '앞서 걷던 렌의 아버지가 멈춰 섰다.' },
  { who: '렌 아버지', text: '가게는 내가 본다. 네가 벽에 스틱 걸어 놓은 거 보는 게 빚보다 더 마음이 무겁다.' },
  { choice: ['"렌, 같이 해요."', '(아무 말도 하지 않는다)'], need: [IF.lv('ren', 2), null], needT: ['렌과 더 가까워져야 한다', ''], ch: 'ren', ex: 'sad', eff: [{ bond: { ren: 3 }, mmt: { ren: 15 }, flags: { renIn3: true } }, { bond: { ren: 1 } }] },
  { if: IF.p(0), who: '렌', ch: 'ren', ex: 'sad', text: '……가게 끝나고요. 열한 시 넘어서.' },
  { if: IF.p(0), who: '렌', ch: 'ren', ex: 'smile', text: '그 시간이면 제가 박자가 제일 잘 맞아요.' },
  { if: IF.p(1), who: '렌', ch: 'ren', ex: 'neutral', text: '여름 지나면요. 여름까지는 가게에 있을게요.' },
  { if: IF.p(1), text: '렌은 아버지를 부축하며 걸었다. 그 걸음도 박자가 일정했다.' },
]);
const E3_2Rb = S('E3_2Rb', '3-2 · 렌 · 가게 빚', [
  { text: '밤 열한 시 반인데 렌이 스튜디오에 오지 않았다. 처음 있는 일이다.' },
  { who: '루이', ch: 'rui', ex: 'pout', text: '연락도 없어. 렌이 이런 적 없잖아.' },
  { bg: 'ramen_night', text: '멘야 도돈에 가 보니 불이 켜져 있다. 렌이 혼자 카운터 안에서 설거지를 하고 있다.' },
  { who: '렌', ch: 'ren', ex: 'surprise', text: '아. ……죄송해요. 시간 봤어야 했는데.' },
  { who: '렌', ch: 'ren', ex: 'sad', text: '아버지가 허리를 다치셔서 오늘부터 제가 마감까지 해요. 당분간 연습 못 갈 것 같아요.' },
  { who: '렌', ch: 'ren', ex: 'sad', text: '가게 빚이 있어서요. 문 닫는 날이 하루라도 생기면 안 돼요.' },
  { choice: ['(앞치마를 두르고 설거지를 돕는다)', '"가게가 먼저야. 연습은 기다릴게."', '"점장님한테 연습실 시간 바꿔 달라고 할게."'], ch: 'ren', ex: 'sad', eff: [{ bond: { ren: 4 }, hp: -10 }, { bond: { ren: 2 }, mmt: { ren: 10 } }, { bond: { ren: 2 }, flags: { lateStudio: true } }] },
  { if: IF.p(0), text: '그릇은 끝이 없었다. 렌이 헹구고 내가 닦는다. 어느새 둘이 같은 박자로 움직이고 있었다.' },
  { if: IF.p(0), who: '렌', ch: 'ren', ex: 'laugh', text: '……지금 우리, 120이에요.' },
  { if: IF.p(1), who: '렌', ch: 'ren', ex: 'sad', text: '기다린다는 말, 오랜만에 들어요.' },
  { if: IF.p(2), who: '렌', ch: 'ren', ex: 'surprise', text: '새벽 한 시에요? 그 시간에 여는 데가 있어요?' },
  { if: IF.p(2), who: '@NAME', text: '0dB 연습실. 점장님이 열쇠 준대.' },
  { who: '렌', ch: 'ren', ex: 'smile', text: '정기 공연 전까지는 어떻게든 맞출게요. 드럼 자리 비우는 일은 없게요.' },
]);

/* ---------- Koto: not in the band → three steps to the door · in the band → her first day in the studio ---------- */
const E3_2Ka = S('E3_2Ka', '3-2 · 코토 · 현관까지 세 걸음', [
  { text: 'kero_P에게서 주소 하나와 짧은 메시지가 DM으로 왔다.' },
  { who: '@kero_P', text: '새 곡 파일이 너무 커서 USB로 드려야 해요. 집 앞까지 와 주실 수 있어요?' },
  { who: '@kero_P', text: '문은 못 열어요. 우편함에 넣어 둘게요.' },
  { if: IF.not(IF.f('kotoName')), who: '@kero_P', text: '아, 문패에 「히나타」라고 있어요. 제 이름은 코토예요. 히나타 코토.', eff: { flags: { kotoName: true } } },
  { bg: 'kotodoor_night', text: '주택가 끝에 있는 이층집이다. 현관 옆 우편함에 개구리 스티커가 붙어 있다.' },
  { text: '우편함 안에 USB가 있다. 이층 창문의 커튼이 살짝 흔들렸다.' },
  { who: '@kero_P', text: '받으셨어요?' },
  { who: '@NAME', text: '받았어. 문 앞에 있어.' },
  { who: '@kero_P', text: '알아요. 보여요.' },
  { text: '한참 뒤, 현관문 너머에서 목소리가 들린다. DM보다 훨씬 작은 목소리다.' },
  { who: '코토', ch: 'koto', ex: 'nervous', text: '……문 앞까지는, 왔어요.' },
  { who: '코토', ch: 'koto', ex: 'nervous', text: '세 걸음이에요. 방에서 여기까지. 오늘은 그게…… 다예요.' },
  { choice: ['"그럼 한 걸음만 더 나와 볼래?"', '"거기서 말해도 들려."', '"다음 공연, 무대 옆자리 비워 둘게."'], need: [IF.lv('koto', 2), null, null], needT: ['코토와 더 가까워져야 한다', '', ''], ch: 'koto', ex: 'nervous', eff: [{ bond: { koto: 4 }, flags: { kotoIn: 'stage' } }, { bond: { koto: 2 } }, { bond: { koto: 2 }, flags: { kotoIn: 'file' } }] },
  { if: IF.p(0), text: '문이 조금 열렸다. 초록 후드 끝이 보인다.' },
  { if: IF.p(0), who: '코토', ch: 'koto', ex: 'surprise', text: '네 걸음. ……됐죠.' },
  { if: IF.p(0), who: '코토', ch: 'koto', ex: 'smile', text: '베이스, 칠게요. 무대 옆에서요. 조명 안 닿는 데서.' },
  { if: IF.p(1), who: '코토', ch: 'koto', ex: 'smile', text: '……네. 들리는구나.' },
  { if: IF.p(1), who: '코토', ch: 'koto', ex: 'neutral', text: '오늘은 여기까지 할게요. 파일은 계속 보낼게요.' },
  { if: IF.p(2), who: '코토', ch: 'koto', ex: 'surprise', text: '무대 옆……' },
  { if: IF.p(2), who: '코토', ch: 'koto', ex: 'nervous', text: '자리만 비워 두세요. 갈 수 있을지는 모르겠지만, 파일로는 같이 할게요.' },
]);
const E3_2Kb = S('E3_2Kb', '3-2 · 코토 · 스튜디오 첫날', [
  { text: '토요일 오후, 스튜디오 문 앞에 초록 후드가 서 있다. 코토가 직접 왔다.' },
  { if: IF.f('kotoIn', 'file'), text: '파일로만 같이 하겠다던 코토가 문 앞까지 와 있다.' },
  { who: '코토', ch: 'koto', ex: 'nervous', text: '……베이스, 직접 치는 게, 나을 것 같아서.' },
  { if: IF.j('natsu'), who: '나츠', ch: 'natsu', ex: 'admire', text: '와! 개구리 후드다! 진짜 눈알 달렸네!' },
  { if: IF.j('natsu'), text: '코토가 말없이 내 등 뒤로 숨었다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '앰프 저기 있어. 볼륨은 네 맘대로 해.' },
  { text: '코토가 베이스를 메고 첫 음을 친다. 다들 순간 조용해진다. 파일로 듣던 그 소리다.' },
  { if: IF.j('rei'), who: '레이', ch: 'rei', ex: 'surprise', text: '……파일보다 좋네.' },
  { who: '코토', ch: 'koto', ex: 'nervous', text: '귀, 괜찮으세요? 저 좀 크게 쳐서.' },
  { text: '코토는 다른 사람 말고 나를 보고 물었다.' },
  { choice: ['"괜찮아."', '"왜 나한테만 물어?"'], ch: 'koto', ex: 'nervous', eff: [{ bond: { koto: 2 } }, { bond: { koto: 3 }, flags: { kotoEar: true } }] },
  { if: IF.p(0), who: '코토', ch: 'koto', ex: 'smile', text: '다행이에요.' },
  { if: IF.p(1), who: '코토', ch: 'koto', ex: 'nervous', text: '그날…… 맨 앞줄에서, 귀 막으시는 거 봤어요.' },
  { if: IF.p(1), who: '코토', ch: 'koto', ex: 'sad', text: '아무한테도 말 안 했어요. 앞으로도 안 할게요.' },
  { if: IF.p(1), text: '코토는 그 말만 하고 다시 베이스를 쳤다. 볼륨이 아까보다 조금 줄어 있었다.' },
]);

/* ---------- Rei: not in the band → the credit · in the band → two metronomes ---------- */
const E3_2Ea = S('E3_2Ea', '3-2 · 레이 · 크레딧', [
  { text: '레코드샵 사이드B 스피커에서 요즘 제일 많이 나오는 곡이 흐른다. ECLIPSE의 신곡이다.' },
  { text: '클래식 코너 앞에 있던 레이가 악보를 덮었다.' },
  { who: '레이', ch: 'rei', ex: 'annoyed', text: '사장님, 이거 꺼 주시면 안 돼요?' },
  { who: '점원', text: '손님들이 틀어 달라고 해서요. 요즘 다들 이것만 찾아요.' },
  { text: '레이가 가게 밖으로 나갔다. 따라 나가 보니 셔터 내린 옆 가게 앞에 서 있다.' },
  { who: '레이', ch: 'rei', ex: 'sad', text: '저 곡 2절 브리지. 스트링 편곡, 내가 했어.' },
  { who: '레이', ch: 'rei', ex: 'neutral', text: '크레딧에는 없어. 리더 이름만 있지. 그땐 그게 당연한 줄 알았어.' },
  { choice: ['"우리 곡엔 네 이름 넣을게. 맨 앞에."', '"……화 안 나?"', '(옆에 같이 서 있는다)'], need: [IF.any(IF.lv('rei', 2), IF.f('reiMaybe')), null, null], needT: ['레이와 더 가까워져야 한다', '', ''], ch: 'rei', ex: 'sad', eff: [{ bond: { rei: 4 }, flags: { reiIn3: true } }, { bond: { rei: 2 } }, { bond: { rei: 2 } }] },
  { if: IF.p(0), who: '레이', ch: 'rei', ex: 'surprise', text: '편곡 크레딧을 맨 앞에?' },
  { if: IF.p(0), who: '@NAME', text: '맨 앞에.' },
  { if: IF.p(0), who: '레이', ch: 'rei', ex: 'shy', text: '말은 쉽게 하네. 좋아. 대신 건반은 내가 쳐. 남이 치면 편곡이 망가지니까.' },
  { if: IF.p(1), who: '레이', ch: 'rei', ex: 'smirk', text: '나지. 근데 화내면 틀린 음이 늘어. 그래서 안 내.' },
  { if: IF.p(2), text: '레이는 가게 안의 곡이 끝나고 다음 곡으로 넘어갈 때까지 아무 말도 하지 않았다.' },
  { if: IF.p(2), who: '레이', ch: 'rei', ex: 'neutral', text: '……아무것도 안 물어봐 줘서 고마워.' },
]);
const E3_2Eb = S('E3_2Eb', '3-2 · 레이 · 메트로놈 두 개', [
  { text: '스튜디오에서 레이의 메트로놈 앱이 딸깍딸깍 돌아간다.' },
  { if: IF.j('natsu'), who: '레이', ch: 'rei', ex: 'annoyed', text: '나츠. 또 빨라.' },
  { if: IF.j('natsu'), who: '나츠', ch: 'natsu', ex: 'pout', text: '신나서 그런 거예요!' },
  { if: IF.j('natsu'), who: '레이', ch: 'rei', ex: 'annoyed', text: '신나면 빨라져도 된다는 법은 없어.' },
  { if: IF.j('natsu'), who: '나츠', ch: 'natsu', ex: 'sad', text: '……선배, 저 그렇게 빨라요?' },
  { if: IF.j('natsu'), choice: ['"조금. 레이 말이 맞아."', '"그 신나는 게 나츠 소리야."', '"둘 다 메트로놈 끄고 한 번 해 보자."'], ch: 'natsu', ex: 'sad', eff: [{ bond: { rei: 2, natsu: -1 } }, { bond: { natsu: 3, rei: -1 } }, { bond: { rei: 1, natsu: 1 }, flags: { metroOff: true } }] },
  { if: IF.all(IF.j('natsu'), IF.p(0)), who: '나츠', ch: 'natsu', ex: 'pout', text: '……알겠어요. 메트로놈이랑 친해져 볼게요.' },
  { if: IF.all(IF.j('natsu'), IF.p(1)), who: '레이', ch: 'rei', ex: 'annoyed', text: '그러다 무대에서 혼자 앞서 나가도 난 모른다.' },
  { if: IF.all(IF.j('natsu'), IF.p(2)), text: '메트로놈을 끄고 한 곡을 쳤다. 나츠는 여전히 조금 빨랐고, 레이는 이번엔 그걸 따라갔다.' },
  { if: IF.all(IF.j('natsu'), IF.p(2)), who: '레이', ch: 'rei', ex: 'shy', text: '……따라간 거 아니야. 맞춰 준 거지.' },
  { if: IF.not(IF.j('natsu')), who: '레이', ch: 'rei', ex: 'annoyed', text: '루이. 후렴에서 늘어져.' },
  { if: IF.not(IF.j('natsu')), who: '루이', ch: 'rui', ex: 'angry', text: '일부러 그러는 거야. 거기서 숨을 쉬어야 다음 소절이 나와.' },
  { if: IF.not(IF.j('natsu')), who: '레이', ch: 'rei', ex: 'neutral', text: '박자를 흔들지 말고 편곡을 바꿔.' },
  { if: IF.not(IF.j('natsu')), choice: ['"레이 말대로 박자를 지키자."', '"루이 숨 쉴 자리를 편곡에 넣자."'], ch: 'rei', ex: 'neutral', eff: [{ bond: { rei: 2, rui: -1 } }, { bond: { rui: 2, rei: 1 }, flags: { ruiBreath: true } }] },
  { if: IF.not(IF.j('natsu')), who: '레이', ch: 'rei', ex: ['smirk', 'neutral'], text: ['그래야지.', '……한 박 반. 그 이상은 못 줘.'] },
  { text: '레이가 메트로놈 앱을 껐다. 연습이 끝났다는 신호다.' },
]);

/* ---------- the fight: whose way ---------- */
const E3_3 = S('E3_3', '3-3 · 불협화음', [
  { text: '정기 공연까지 3주 남았다. 스튜디오 분위기가 무겁다.' },
  { text: '같은 곡에서 벌써 세 번째로 멈췄다.' },
  { if: IF.j('rei'), who: '레이', ch: 'rei', ex: 'annoyed', text: '또 흔들렸어. 이러면 서른 명 앞에서 망신이야.' },
  { if: IF.j('natsu'), who: '나츠', ch: 'natsu', ex: 'pout', text: '매번 멈추니까 신나는 게 다 사라지잖아요!' },
  { if: IF.j('ren'), who: '렌', ch: 'ren', ex: 'neutral', text: '제가 템포를 잡을게요. 다들 드럼만 들어 주세요.' },
  { if: IF.j('koto'), text: '코토가 휴대폰 화면을 내민다. 바로 옆에 있는데 DM이 와 있다. 「곡 구성을 바꾸면 어때요. 새 곡 써 왔어요」.' },
  { who: '루이', ch: 'rui', ex: 'angry', text: '다들 좀 조용히 해.' },
  { who: '루이', ch: 'rui', ex: 'sad', text: '뒤가 이렇게 시끄러우면 목소리가 안 나와.' },
  { text: '다들 입을 다물었다. 그리고 다 같이 이쪽을 봤다.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '네가 정해. 이번 공연, 누구 방식으로 갈지.' },
  { choice: ['루이의 목소리에 맞춘다', '렌의 드럼에 맞춘다', '레이의 편곡대로 간다', '코토의 새 곡으로 간다', '나츠의 소리를 앞에 세운다'], need: [null, IF.j('ren'), IF.j('rei'), IF.j('koto'), IF.j('natsu')], needT: ['', '밴드에 렌이 없다', '밴드에 레이가 없다', '밴드에 코토가 없다', '밴드에 나츠가 없다'], ch: 'rui', ex: 'neutral',
    eff: [{ flags: { center: 'rui' }, bond: { rui: 4 } }, { flags: { center: 'ren' }, bond: { ren: 4 } }, { flags: { center: 'rei' }, bond: { rei: 4, natsu: -1 } }, { flags: { center: 'koto' }, bond: { koto: 4 } }, { flags: { center: 'natsu' }, bond: { natsu: 4, rei: -1 } }] },
  { if: IF.p(0), who: '루이', ch: 'rui', ex: 'surprise', text: '……나?' },
  { if: IF.p(0), who: '루이', ch: 'rui', ex: 'shy', text: '알았어. 후회하지 마.' },
  { if: IF.p(1), who: '렌', ch: 'ren', ex: 'surprise', text: '제가요?' },
  { if: IF.p(1), who: '렌', ch: 'ren', ex: 'smile', text: '……네. 카운트부터 다시 할게요.' },
  { if: IF.p(2), who: '레이', ch: 'rei', ex: 'smirk', text: '당연한 선택이네. 악보는 오늘 밤에 보낼게.' },
  { if: IF.all(IF.p(2), IF.j('natsu')), who: '나츠', ch: 'natsu', ex: 'pout', text: '……또 메트로놈이에요?' },
  { if: IF.p(3), text: '코토가 후드를 더 깊이 눌러썼다. 휴대폰에 DM이 하나 더 왔다. 「진짜요?」' },
  { if: IF.p(4), who: '나츠', ch: 'natsu', ex: 'admire', text: '저요?! 진짜요?!' },
  { if: IF.p(4), who: '레이', ch: 'rei', ex: 'annoyed', text: '……책임은 네가 져.' },
  { text: '누군가는 웃었고 누군가는 한숨을 쉬었다. 그래도 아무도 스튜디오를 나가지 않았다.' },
]);

/* ---------- 3-4 · five ways ---------- */
const E3_4a = S('E3_4a', '3-4 · 루이 · 마스크 너머', [
  { text: '루이의 목소리에 맞춰 곡을 다시 짠다. 키를 반음 내리고, 후렴 앞에 숨 쉴 자리를 한 박 넣었다.' },
  { text: '연습이 끝나고 둘만 남았다. 루이가 마스크 끈을 만지작거린다.' },
  { who: '루이', ch: 'rui', ex: 'sad', text: '……나 아이돌 연습생이었어.' },
  { who: '루이', ch: 'rui', ex: 'sad', text: '데뷔조 평가 날, 첫 소절부터 목소리가 안 나왔어.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '심사위원들이 다 보고 있었어. 그 얼굴들이 아직도 생각나.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '그 뒤로 이걸 쓰면 목소리가 나와. 얼굴을 안 보여 주면 괜찮더라.' },
  { choice: ['"무대에서 굳는 게 어떤 건지 알아."', '"안 벗어도 돼."', '(끝까지 듣는다)'], ch: 'rui', ex: 'neutral', eff: [{ bond: { rui: 3 }, mt: -2 }, { bond: { rui: 2 } }, { bond: { rui: 2 } }] },
  { who: '루이', ch: 'rui', ex: ['sad', 'shy', 'neutral'], text: ['……알지. 너는 알지. 그래서 너한테 말하는 거야.', '벗으라고 할 줄 알았어. 다들 그러니까.', '다 듣고 나서 아무 말도 안 하는 거, 그거 좋다.'] },
  { who: '루이', ch: 'rui', ex: 'smile', text: '이번 공연은 내 목소리 기준이야. 그러니까 이번엔 나 믿어.' },
]);
const E3_4b = S('E3_4b', '3-4 · 렌 · 140', [
  { text: '렌의 드럼에 모두 맞추기로 했다. 렌은 카운트를 평소보다 크게 센다.' },
  { text: '새벽 한 시, 연습이 끝나고 렌과 단둘이 장비를 정리한다.' },
  { who: '렌', ch: 'ren', ex: 'neutral', text: '무대에서는 드럼이 멈추면 다 멈춰요.' },
  { who: '렌', ch: 'ren', ex: 'sad', text: '그게 무서워서 봄까지만 한다고 한 것도 있어요. 빚 핑계를 대면서요.' },
  { choice: ['"나는 쉼표가 무서워."', '"멈추면 내가 이어서 칠게."'], ch: 'ren', ex: 'sad', eff: [{ bond: { ren: 3 }, mt: 2 }, { bond: { ren: 3 } }] },
  { who: '렌', ch: 'ren', ex: ['surprise', 'smile'], text: ['……쉼표요?', '네 개 다 치시니까요. 든든하네요.'] },
  { if: IF.p(0), who: '렌', ch: 'ren', ex: 'smile', text: '그럼 쉼표에서도 하이햇은 계속 칠게요. 아주 작게요. 박자가 안 끊기게.' },
  { who: '렌', ch: 'ren', ex: 'shy', text: '지금 심박 140이에요. 템포 얘기예요. ……반쯤은요.' },
]);
const E3_4c = S('E3_4c', '3-4 · 레이 · Opus 0', [
  { text: '레이가 밤새 고친 악보를 보내왔다. 파일 이름이 「Opus 0」으로 되어 있다.' },
  { text: '악보 맨 위에 작은 글씨로 「편곡 · 시라유키 레이」라고 적혀 있다.' },
  { who: '레이', ch: 'rei', ex: 'neutral', text: '거기 이름, 네가 넣으라고 했잖아. 그래서 넣었어.' },
  { who: '레이', ch: 'rei', ex: 'annoyed', text: '틀린 데 있으면 말해. 없겠지만.' },
  { text: '편곡은 정확했다. 다들 조금씩 덜 치니까, 그 빈자리 덕분에 곡에 여유가 생긴다.' },
  { choice: ['"네 이름이 잘 어울려."', '"두 번째 마디, 하나 틀렸어."'], ch: 'rei', ex: 'annoyed', eff: [{ bond: { rei: 3 } }, { bond: { rei: 4 } }] },
  { who: '레이', ch: 'rei', ex: ['shy', 'surprise'], text: ['……그런 말 하지 마. 박자 흔들려.', '어디? ……진짜네.'] },
  { if: IF.p(1), who: '레이', ch: 'rei', ex: 'smirk', text: '고칠게. 너 같은 사람이 있어야 편곡이 늘어.' },
]);
const E3_4d = S('E3_4d', '3-4 · 코토 · 세 번째 곡', [
  { text: '코토의 새 곡을 세 번째 곡으로 넣기로 했다. 가사는 아직 없고, 베이스가 먼저 멜로디를 치는 곡이다.' },
  { text: '밤에 코토에게서 DM이 연달아 온다.' },
  { who: '@kero_P', text: '가사는 루이 씨가 써 주시면 좋겠어요. 저는 말을 잘 못 써서요.' },
  { who: '@kero_P', text: '곡 제목은 정했어요. 「우물 밖」.' },
  { who: '@kero_P', text: '제 방이 우물이에요. 1년 전 그날, 페스티벌 갈 때만 밖에 나갔었어요.' },
  { who: '@kero_P', text: '그날 이후로 다시 우물로 들어갔는데, 요즘은 가끔 밖에 나가요. 스튜디오까지요.' },
  { choice: ['"좋은 제목이야."', '"그날 왜 밖에 나왔어?"'], eff: [{ bond: { koto: 2 } }, { bond: { koto: 3 } }] },
  { if: IF.p(1), who: '@kero_P', text: '좋아하는 밴드가 나와서요.' },
  { if: IF.p(1), who: '@kero_P', text: '……지금도 좋아해요. 그 밴드 사람.' },
  { if: IF.p(1), text: '답장을 쓰기 전에 DM이 하나 더 왔다. 「방금 거 지워도 돼요?」 지울 수 있는 기능은 없다.' },
  { if: IF.p(0), who: '@kero_P', text: '(개구리 이모티콘 세 개)' },
]);
const E3_4e = S('E3_4e', '3-4 · 나츠 · F에서 B♭까지', [
  { text: '나츠의 기타를 앞에 세우기로 했다. 첫 음은 나츠가 친다.' },
  { text: '연습이 끝나고 강변 둑에 앉았다. 나츠가 캔 커피 두 개를 사 왔다.' },
  { who: '나츠', ch: 'natsu', ex: 'shy', text: '선배, 저 그 영상 몇천 번 봤다고 했잖아요.' },
  { who: '나츠', ch: 'natsu', ex: 'neutral', text: '웃기려고 본 게 아니에요. 소리가 계속 이상해서요.' },
  { who: '나츠', ch: 'natsu', ex: 'neutral', text: '전날 리허설 때 펜스 밖에서 몰래 들었거든요. 그때 기타 소리랑, 방송에 나온 소리가 달랐어요.' },
  { who: '나츠', ch: 'natsu', ex: 'sad', text: '방송 쪽이 너무 깨끗했어요. 선배는 늘 두 번째 줄을 살짝 늦게 치는 버릇이 있는데, 그게 없었어요.' },
  { text: '캔을 쥔 손에 힘이 들어갔다.', eff: { mt: -3 } },
  { choice: ['"……그 얘기, 누구한테 했어?"', '"버릇까지 알아?"'], ch: 'natsu', ex: 'sad', eff: [{ bond: { natsu: 2 }, flags: { natsuHint: true } }, { bond: { natsu: 3 }, flags: { natsuHint: true } }] },
  { who: '나츠', ch: 'natsu', ex: ['sad', 'grin'], text: ['아무한테도요. 제가 틀렸을 수도 있으니까요.', '그럼요! 몇천 번 봤다니까요!'] },
  { who: '나츠', ch: 'natsu', ex: 'grin', text: '그러니까 이번엔 제가 제일 크게 칠게요. 선배 버릇 그대로 따라서요.' },
]);

/* ---------- the business card ---------- */
const E3_5 = S('E3_5', '3-5 · 명함', [
  { text: '평일 밤 0dB 손님 중에 정장 차림이 한 명 있다. 이런 가게에서는 눈에 띈다.' },
  { text: '공연이 끝나고 케이블을 감는데 그 사람이 다가왔다.' },
  { who: '미카미 쇼고', text: '오랜만이에요. 기억하려나. 블루 아워 페스 대기실에서 한 번 인사했는데.' },
  { text: '기억한다. 그날 대기실에서 방송 쪽은 걱정하지 말라던 목소리다.' },
  { who: '미카미 쇼고', text: '크레셴도 레코드 미카미예요. 영상 봤어요. 새 밴드 좋던데요.' },
  { who: '미카미 쇼고', text: '그날 일은 정말 안타까웠어요. 우리도 할 수 있는 건 다 했는데.' },
  { who: '미카미 쇼고', text: '명함 드릴게요. 무슨 일 있으면 연락 줘요. 하루 군도 가끔 당신 얘기를 하거든요.' },
  { choice: ['(명함을 받는다)', '"필요 없어요."', '"하루가 제 얘기를 해요?"'], eff: [{ mt: -3, flags: { mikamiCard: true } }, { mt: 2 }, { mt: -5, flags: { mikamiCard: true, askedHaru: true } }] },
  { if: IF.p(1), who: '미카미 쇼고', text: '그래요. 마음 바뀌면 점장님한테 물어봐요.' },
  { if: IF.p(2), who: '미카미 쇼고', text: '그럼요. 좋은 얘기만 해요. 걱정 마요.' },
  { text: '미카미가 계단을 올라가자 점장이 카운터에서 나왔다.' },
  { who: '세리자와 점장', text: '저 사람이 왜 여기 와.' },
  { if: IF.f('mikamiCard'), who: '세리자와 점장', text: '명함 받았으면 서랍에 넣어 둬. 버리지는 말고. 나중에 필요할지도 몰라.' },
  { if: IF.not(IF.f('mikamiCard')), who: '세리자와 점장', text: '잘했어. 저런 사람은 웃으면서 계산기 두드려.' },
  { text: '케이블을 마저 감는다. 손이 조금 떨려서 한 번 꼬였다.' },
]);

/* ---------- the regular show ---------- */
const E3_6 = S('E3_6', '3-6 · 정기 공연', [
  { text: '6월 28일 토요일 저녁, 0dB 정기 공연 날이다.' },
  { text: '대기실까지 객석 소리가 들린다. 지난번보다 훨씬 시끄럽다.' },
  { who: '세리자와 점장', text: '서른두 명. 표는 너희가 팔았고. 잘했어.' },
  { if: IF.f('center', 'rui'), who: '루이', ch: 'rui', ex: 'neutral', text: '오늘은 내 목소리에 맞춰. 네가 그렇게 정했으니까.' },
  { if: IF.f('center', 'ren'), who: '렌', ch: 'ren', ex: 'neutral', text: '카운트는 제가 할게요. 다들 드럼만 들으세요.' },
  { if: IF.f('center', 'rei'), who: '레이', ch: 'rei', ex: 'neutral', text: '편곡대로만 쳐. 틀리면 내가 다 들어.' },
  { if: IF.f('center', 'koto'), text: '앰프 뒤의 코토가 휴대폰을 들어 보인다. 「세 번째 곡, 제 곡이에요. 떨려요」.' },
  { if: IF.f('center', 'natsu'), who: '나츠', ch: 'natsu', ex: 'grin', text: '첫 음은 제가 칠게요! 제일 크게요!' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '……가자.' },
]);
const E3_6M = S('E3_6M', '3-6 · 곡 사이', [
  { text: '첫 곡이 끝났다. 서른두 명의 박수는 다섯 명 때와 소리부터 다르다.' },
  { text: '두 번째 곡은 반 박자 곡이다. 이제는 이 곡을 칠 때 손이 덜 차갑다.' },
]);
const E3_7S = S('E3_7S', '3-7S · 따라 부르는 소리', [
  { text: '세 번째 곡, 마지막 후렴 앞에 한 마디 쉼표가 온다.' },
  { text: '그 한 마디에 객석에서 소리가 들렸다. 몇 명이 후렴을 먼저 따라 부르고 있었다.' },
  { text: '이번에는 그 소리가 또렷하게 들렸다.' },
  { text: '셋에 다시 들어갔다. 쉼표가 무섭지 않았던 건 처음이다.', eff: { mt: 8 } },
  { bg: 'backstage', who: '세리자와 점장', text: '다음 달도 너희야. 이번엔 마흔 명.' },
  { if: IF.f('center', 'rui'), who: '루이', ch: 'rui', ex: 'smile', text: '들었어? 내 노래를 따라 불렀어.' },
  { if: IF.f('center', 'ren'), who: '렌', ch: 'ren', ex: 'laugh', text: '쉼표에서도 하이햇 계속 쳤어요. 들렸어요?' },
  { if: IF.f('center', 'rei'), who: '레이', ch: 'rei', ex: 'smile', text: '……틀린 음 하나. 오늘은 그걸로 됐어.' },
  { if: IF.f('center', 'koto'), text: '코토에게서 「제 곡을 누가 따라 불렀어요」라는 DM이 왔다. 그 뒤로는 개구리 이모티콘만 스무 개가 왔다.' },
  { if: IF.f('center', 'natsu'), who: '나츠', ch: 'natsu', ex: 'admire', text: '선배! 저 오늘 한 번도 안 틀렸어요! ……아마도요!' },
]);
const E3_7B = S('E3_7B', '3-7B · 멈춘 두 마디', [
  { text: '세 번째 곡의 마지막 후렴 앞 쉼표에서 손이 멈췄다.' },
  { text: '한 마디, 두 마디가 지나간다. 객석이 술렁이는 소리가 멀게 들린다.', fx: 'tinnitus', eff: { mt: -4 } },
  { if: IF.f('center', 'rui'), text: '루이가 오픈 마이크 때처럼, 원래 그런 곡인 것처럼 혼자 노래를 이었다.' },
  { if: IF.f('center', 'ren'), text: '하이햇이 작게 계속 울리고 있었다. 렌이다. 그 박자를 따라 셋에 들어갔다.' },
  { if: IF.f('center', 'rei'), text: '건반이 빈자리를 메웠다. 레이의 편곡에는 원래 없던 음이다.' },
  { if: IF.f('center', 'koto'), text: '베이스가 멜로디를 쳤다. 코토가 앰프 뒤에서 나와 있었다.' },
  { if: IF.f('center', 'natsu'), text: '나츠의 기타가 크게 울렸다. 틀린 코드였지만 아무도 신경 쓰지 않았다.' },
  { bg: 'backstage', text: '공연이 끝난 대기실에서 다들 아무 말이 없다.' },
  { who: '루이', ch: 'rui', ex: 'sad', text: '……다음 달에 또 하면 돼.' },
  { text: '루이의 목소리가 평소보다 조금 부드러웠다.' },
]);

/* ---------- the first piece of the 47 seconds ---------- */
const E3_8 = S('E3_8', '3-8 · 끊긴 건 방송 라인뿐', [
  { text: '정기 공연 이틀 뒤, 점장이 가게 문을 닫고 한 사람을 데려왔다.' },
  { who: '세리자와 점장', text: '오카베. 옛날에 나랑 같이 무대 뛰던 음향 엔지니어야. 지금은 페스 PA 일을 해.' },
  { who: '오카베', text: '반가워요. 토요일 공연 봤어요. 맨 뒤에서.' },
  { if: IF.f('askedBroadcast'), who: '세리자와 점장', text: '예전에 그날 조명 얘기 나중에 하자고 했지. 지금 할게.' },
  { who: '오카베', text: '작년 블루 아워 페스요. 서브 스테이지 PA 콘솔 옆에 제가 있었어요.' },
  { who: '오카베', text: '그 47초 동안 행사장 전원은 멀쩡했어요. 조명도, 모니터도, 제 콘솔도요.' },
  { who: '오카베', text: '끊긴 건 방송 라인이랑 메인 PA로 가는 라인, 그 두 개뿐이었어요. 무대 뒤 재생 장비 쪽에서요.' },
  { who: '@NAME', text: '재생 장비요? 그날 우리는 전부 라이브로 쳤는데요.' },
  { who: '오카베', text: '그러니까 이상하다는 거예요. 무대 뒤에 저희 쪽 장비가 아닌 게 하나 있었어요. 레이블 쪽에서 들여온 거요.' },
  { who: '오카베', text: '누가 뭘 틀려고 했는지는 몰라요. 저는 콘솔만 봤으니까.' },
  { text: '그날 인이어로 들은 소리가 다시 떠오른다. 기타 소리는 끝까지 들렸다. 내가 친 것치고는 너무 깨끗한 소리였다.', fx: 'tinnitus' },
  { if: IF.f('natsuHint'), text: '두 번째 줄을 살짝 늦게 치는 버릇이 없었다던 나츠의 말도 떠오른다.' },
  { choice: ['"더 아는 건 없어요?"', '"……감사합니다."'], eff: [{ mt: -3 }, { mt: -1 }] },
  { who: '오카베', text: ['없어요. 있었으면 1년 동안 입 다물고 있지 않았겠죠. 미안해요.', '고마워할 일은 아니에요. 늦게 말해서 미안해요.'] },
  { who: '세리자와 점장', text: '그날 조명이 켜져 있던 이유가 이거야. 너 때문에 소리가 끊긴 게 아니라는 거.' },
  { text: '내 탓이 아니었을 수도 있다니, 1년 동안 한 번도 못 해 본 생각이다.', eff: { mt: 6 } },
]);
const E3_9 = S('E3_9', '3-9 · ECLIPSE', [
  { text: '7월 첫 월요일, PULSE 트렌드 1위에 익숙한 이름이 떠 있다.' },
  { who: 'PULSE', text: '@ECLIPSE_official · 여름 대항전 시리즈 「ECLIPSE vs NEXT」 개최. 도전 밴드 모집.' },
  { who: 'PULSE', text: '@ECLIPSE_official · 기타 츠키시마 하루 코멘트: "꼭 같은 무대에 서 보고 싶은 밴드가 있어요."' },
  { text: '사진 속 하루는 1년 전보다 머리가 짧다. 웃고 있다. 그 얼굴을 한참 봤다.' },
  { text: '귀 안쪽이 다시 울렸다.', fx: 'tinnitus', eff: { mt: -4 } },
  { bg: 'backstage', who: '루이', ch: 'rui', ex: 'neutral', text: '……봤어?' },
  { if: IF.j('rei'), who: '레이', ch: 'rei', ex: 'annoyed', text: 'ECLIPSE네. 리더 얼굴은 별로 보고 싶지 않은데.' },
  { if: IF.j('natsu'), who: '나츠', ch: 'natsu', ex: 'surprise', text: '하루면…… 그 하루요? 배신자라고 다들 그러는?' },
  { if: IF.j('natsu'), who: '루이', ch: 'rui', ex: 'angry', text: '나츠.' },
  { who: '루이', ch: 'rui', ex: 'neutral', text: '나가자. 대항전.' },
  { choice: ['"……나가자."', '"조금만 생각해 볼게."'], ch: 'rui', ex: 'neutral', eff: [{ bond: { rui: 2 }, flags: { battle: 'yes' } }, { flags: { battle: 'think' } }] },
  { who: '루이', ch: 'rui', ex: ['smile', 'neutral'], text: ['그래. 이번엔 네가 먼저 말했다.', '생각은 해. 대신 도망은 가지 마.'] },
  { text: '그날 밤, 1년 동안 한 번도 울리지 않던 대화방에 알림이 떴다.', fx: 'buzz' },
  { who: '하루', text: '토요일 공연, 뒤에서 봤어.' },
  { who: '하루', text: '쉼표에서 안 멈추더라.', if: IF.rk('3-6', 3) },
  { who: '하루', text: '쉼표에서 멈추는 거, 아직 그대로네.', if: IF.not(IF.rk('3-6', 3)) },
  { text: '답장을 쓰다가 지웠다. 쓰다가 또 지웠다. 화면이 꺼질 때까지 그러고 있었다.' },
]);

CH[3] = {
  no: '03', en: 'CHAPTER 3', name: '불협화음', bg: 'studio', span: '5월 말 ~ 6월 · 정기 공연',
  desc: '첫 공연 영상이 퍼진다. 빈자리를 채우고, 누구를 중심으로 밴드를 끌고 갈지 정해야 한다.',
  goals: g => [['빈자리 채우기', g.joined.length >= 4], ['밴드의 중심 정하기', !!g.flags.center], ['정기 공연', !!g.ep['3-6']], ['47초의 첫 조각', !!g.flags.frag1]],
  show: '3-6', showName: 'REGULAR SHOW', end: '3-9',
  forks: [{ c: 1, t: '상태 · 렌' }, { c: 2, t: '상태 · 코토' }, { c: 3, t: '상태 · 레이' }, { c: 5, t: '선택 · 밴드의 중심' }, { c: 8, t: '결과 · 정기 공연 랭크' }],
  nodes: [
    { id: '3-1', c: 0, l: 2, type: 'talk', t: '공연 다음 날', day: 42, time: '저녁', desc: '금요일 공연 영상이 PULSE에 퍼진다. 점장이 다음 공연을 제안한다.', chg: ['정기 공연 날짜가 정해진다', '나츠를 기다리게 했다면 여기서 합류'], rw: [], from: ['2-9'],
      steps: [{ adv: E3_1, bg: 'river_day', place: '<b>집</b> · 월요일 아침' }], eff: g => ({ flags: { in3: { ren: g.joined.includes('ren'), koto: g.joined.includes('koto'), rei: g.joined.includes('rei') } } }) },
    { id: '3-2Ra', c: 1, l: 1, type: 'ev', who: 'ren', t: '새벽 시장', day: 45, time: '새벽', alt: true, desc: '렌이 아직 밴드에 없다. 새벽 어시장에서 렌과 렌의 아버지를 만난다.', chg: ['렌 ♥LV2 이상이면 렌 합류'], rw: ['렌 ♥'], from: ['3-1'], when: IF.not(in3('ren')),
      steps: [{ adv: E3_2Ra, bg: 'street', place: '<b>나기사카</b> 어시장 · 새벽' }], eff: g => g.flags.renIn3 ? { join: 'ren' } : {}, log: g => g.flags.renIn3 ? '새벽 시장 · 렌 합류' : '렌은 여름까지 가게에' },
    { id: '3-2Rb', c: 1, l: 3, type: 'ev', who: 'ren', t: '가게 빚', day: 45, time: '밤', alt: true, desc: '렌이 처음으로 연습에 오지 않았다.', chg: ['렌 멘탈 ±', '연습 시간이 바뀔 수 있다'], rw: ['렌 ♥'], from: ['3-1'], when: in3('ren'),
      steps: [{ adv: E3_2Rb, bg: 'studio_night', place: '<b>UNDERPASS 스튜디오</b> · 밤' }] },
    { id: '3-2Ka', c: 2, l: 1, type: 'ev', who: 'koto', t: '현관까지 세 걸음', day: 49, time: '밤', alt: true, desc: '코토가 아직 밴드에 없다. 새 곡 USB를 집 우편함에 넣어 두겠다고 한다.', chg: ['코토 ♥LV2 이상이면 문 앞까지 나온다', 'TOWN에 코토네 집 앞이 열린다'], rw: ['코토 ♥'], from: ['3-2Ra', '3-2Rb'], when: IF.not(in3('koto')),
      steps: [{ adv: E3_2Ka, bg: 'kotodoor_night', place: '<b>PULSE</b> DM · 밤' }], eff: g => ({ flags: { kotoDoor: true }, ...(g.flags.kotoIn ? { join: 'koto' } : {}) }), log: g => g.flags.kotoIn ? '코토 합류' : '코토는 문 너머에서' },
    { id: '3-2Kb', c: 2, l: 3, type: 'ev', who: 'koto', t: '스튜디오 첫날', day: 49, time: '오후', alt: true, desc: '코토가 처음으로 스튜디오에 직접 온다.', chg: ['코토가 그날 본 것을 하나 말할 수도 있다'], rw: ['코토 ♥'], from: ['3-2Ra', '3-2Rb'], when: in3('koto'),
      steps: [{ adv: E3_2Kb, bg: 'studio', place: '<b>UNDERPASS 스튜디오</b> · 토요일' }], eff: { flags: { kotoDoor: true, kotoStudio: true } } },
    { id: '3-2Ea', c: 3, l: 1, type: 'ev', who: 'rei', t: '크레딧', day: 53, time: '저녁', alt: true, desc: '레이가 아직 밴드에 없다. 레코드샵에 ECLIPSE의 신곡이 흐른다.', chg: ['레이 ♥LV2 이상이거나 2장에서 여지를 남겼다면 레이 합류'], rw: ['레이 ♥'], from: ['3-2Ka', '3-2Kb'], when: IF.not(in3('rei')),
      steps: [{ adv: E3_2Ea, bg: 'record_night', place: '<b>레코드샵 사이드B</b> · 저녁' }], eff: g => g.flags.reiIn3 ? { join: 'rei' } : {}, log: g => g.flags.reiIn3 ? '크레딧을 약속했다 · 레이 합류' : '레이는 아직' },
    { id: '3-2Eb', c: 3, l: 3, type: 'ev', who: 'rei', t: '메트로놈 두 개', day: 53, time: '밤', alt: true, desc: '레이의 메트로놈이 누군가와 부딪힌다.', chg: ['누구 편을 드는지에 따라 ♥가 갈린다'], rw: ['♥ ±'], from: ['3-2Ka', '3-2Kb'], when: in3('rei'),
      steps: [{ adv: E3_2Eb, bg: 'studio_night', place: '<b>UNDERPASS 스튜디오</b> · 밤' }] },
    { id: '3-3', c: 4, l: 2, type: 'talk', t: '불협화음', day: 60, time: '밤', desc: '같은 곡을 세 번째 멈췄다. 모두가 이쪽을 본다.', chg: ['누구의 방식으로 갈지 정한다 → 3-4가 다섯 갈래로 나뉜다'], rw: ['고른 멤버 ♥+4'], from: ['3-2Ea', '3-2Eb'],
      steps: [{ adv: E3_3, bg: 'studio_night', place: '<b>UNDERPASS 스튜디오</b> · 밤' }], log: g => `밴드의 중심 · ${nm(g.flags.center)}` },
    { id: '3-4a', c: 5, l: 0, type: 'ev', who: 'rui', t: '마스크 너머', day: 63, time: '밤', alt: true, desc: '루이의 목소리에 맞춰 곡을 다시 짠다. 연습이 끝나고 둘만 남는다.', chg: ['루이가 마스크를 쓰는 이유를 말한다'], rw: ['루이 ♥'], from: ['3-3'], when: IF.f('center', 'rui'), steps: [{ adv: E3_4a, bg: 'studio_night', place: '<b>UNDERPASS 스튜디오</b> · 밤' }] },
    { id: '3-4b', c: 5, l: 1, type: 'ev', who: 'ren', t: '140', day: 63, time: '새벽', alt: true, desc: '렌의 드럼에 모두 맞춘다. 새벽 한 시, 장비를 정리하며.', chg: ['렌이 드럼을 그만두려던 진짜 이유'], rw: ['렌 ♥'], from: ['3-3'], when: IF.f('center', 'ren'), steps: [{ adv: E3_4b, bg: 'studio_night', place: '<b>0dB</b> 연습실 · 새벽' }] },
    { id: '3-4c', c: 5, l: 2, type: 'ev', who: 'rei', t: 'Opus 0', day: 63, time: '밤', alt: true, desc: '레이가 밤새 고친 악보를 보내온다.', chg: ['레이의 이름이 처음으로 악보에 남는다'], rw: ['레이 ♥'], from: ['3-3'], when: IF.f('center', 'rei'), steps: [{ adv: E3_4c, bg: 'studio_night', place: '<b>UNDERPASS 스튜디오</b> · 밤' }] },
    { id: '3-4d', c: 5, l: 3, type: 'ev', who: 'koto', t: '세 번째 곡', day: 63, time: '밤', alt: true, desc: '코토의 새 곡을 세 번째 곡으로 넣는다.', chg: ['코토가 1년 전 그날 밖에 나온 이유'], rw: ['코토 ♥'], from: ['3-3'], when: IF.f('center', 'koto'), steps: [{ adv: E3_4d, bg: 'river_night', place: '<b>PULSE</b> DM · 밤' }] },
    { id: '3-4e', c: 5, l: 4, type: 'ev', who: 'natsu', t: 'F에서 B♭까지', day: 63, time: '밤', alt: true, desc: '나츠의 기타를 앞에 세운다. 연습이 끝나고 강변 둑에서.', chg: ['나츠가 그날 들은 소리'], rw: ['나츠 ♥'], from: ['3-3'], when: IF.f('center', 'natsu'), steps: [{ adv: E3_4e, bg: 'river_night', place: '<b>강변 둑길</b> · 밤' }] },
    { id: '3-5', c: 6, l: 2, type: 'talk', t: '명함', day: 70, time: '밤', desc: '0dB 객석에 정장 차림의 남자가 있다. 그날 대기실에서 들은 목소리다.', chg: ['명함을 받을지 정한다'], rw: [], from: ['3-4a', '3-4b', '3-4c', '3-4d', '3-4e'],
      steps: [{ adv: E3_5, bg: 'stage', place: '<b>0dB</b> · 평일 밤' }], log: g => g.flags.mikamiCard ? '미카미의 명함을 받았다' : '미카미의 명함을 거절했다' },
    { id: '3-6', c: 7, l: 2, type: 'live', t: '정기 공연', day: 82, time: '저녁', desc: '0dB 정기 공연. 관객 서른두 명. 밴드의 중심에 따라 무대가 달라진다.', chg: ['마지막 곡 랭크 A 이상 → 「따라 부르는 소리」', 'B 이하 → 「멈춘 두 마디」'], rw: ['팬', '¥', 'SYNC'], from: ['3-5'], need: { fans: 1000, lives: 6 },
      steps: [{ adv: E3_6, bg: 'backstage', place: '<b>0dB</b> 대기실 · 토요일 저녁' }, { live: { song: 'count4', len: 'hl', bg: 'stage', party: 'band', ask: '첫 곡 · カウント四つ에서 칠 악기' } }, { adv: E3_6M, bg: 'stage', place: '<b>0dB</b> · 곡 사이' }, { live: { song: 'hanpaku', len: 'hl', bg: 'stage', party: 'band', ask: '두 번째 곡 · 半拍ずれたまま에서 칠 악기' } }],
      log: g => `정기 공연 · ${g.ep['3-6'] && g.ep['3-6'].rank}랭크` },
    { id: '3-7S', c: 8, l: 1, type: 'cut', t: '따라 부르는 소리', day: 82, time: '밤', alt: true, desc: '마지막 후렴 앞 쉼표. 객석에서 소리가 들린다.', chg: ['쉼표가 처음으로 무섭지 않다'], rw: ['팬 +150', '멘탈 +8'], from: ['3-6'], when: IF.rk('3-6', 3),
      steps: [{ adv: E3_7S, bg: 'stage', place: '<b>0dB</b> 정기 공연 · 세 번째 곡' }], eff: g => ({ fans: 150, bond: { [g.flags.center || 'rui']: 2 } }) },
    { id: '3-7B', c: 8, l: 3, type: 'talk', t: '멈춘 두 마디', day: 82, time: '밤', alt: true, desc: '마지막 후렴 앞에서 손이 멈췄다. 밴드가 그 자리를 메운다.', chg: ['중심 멤버가 빈자리를 메운다'], rw: ['팬 +60', '중심 멤버 ♥+3'], from: ['3-6'], when: IF.not(IF.rk('3-6', 3)),
      steps: [{ adv: E3_7B, bg: 'stage', place: '<b>0dB</b> 정기 공연 · 세 번째 곡' }], eff: g => ({ fans: 60, bond: { [g.flags.center || 'rui']: 3 } }) },
    { id: '3-8', c: 9, l: 2, type: 'talk', t: '끊긴 건 방송 라인뿐', day: 84, time: '밤', desc: '점장이 옛 음향 엔지니어 친구를 데려온다. 1년 전 그날 PA 콘솔 옆에 있던 사람이다.', chg: ['47초의 진실 조각 #1'], rw: ['조각 #1', '멘탈 +'], from: ['3-7S', '3-7B'],
      steps: [{ adv: E3_8, bg: 'backstage', place: '<b>0dB</b> · 문 닫은 뒤' }], eff: { flags: { frag1: true } }, log: '조각 #1 · 끊긴 건 방송과 PA 라인뿐' },
    { id: '3-9', c: 10, l: 2, type: 'cut', t: 'ECLIPSE', day: 91, time: '밤', desc: 'PULSE 트렌드 1위에 익숙한 이름이 떠 있다.', chg: ['대항전에 나갈지', 'CHAPTER 4로 이어진다'], rw: [], from: ['3-8'],
      steps: [{ adv: E3_9, bg: 'river_night', place: '<b>나기사카</b> · 7월 첫 월요일' }], log: g => g.flags.battle === 'yes' ? '대항전에 나가기로 했다' : '대항전은 생각해 보기로 했다' },
  ],
};
